//! Generate `pub const NAME: u32` + `inventory::submit!(AddrEntry { ... })`
//! lines for every function (and global) in the catalog.
//!
//! Output format is included by `crates/openwa-game/src/generated/mod.rs` via
//! `include!(concat!(env!("OUT_DIR"), "/generated_addresses.rs"))`. The
//! generated module pulls names directly from `Function.name` / `Global.name`,
//! so e.g. `GameRuntime__StepFrame` becomes `generated::addresses::GameRuntime__StepFrame`.
//!
//! Coexistence with hand-written `define_addresses!`: both emit to the same
//! `inventory::collect!(AddrEntry)` bucket. The registry sorts so Manual wins
//! at any VA where both exist (see
//! `crates/openwa-game/src/registry.rs::source_rank`). Duplicate inventory
//! entries are harmless — total memory is small and `lookup_va` is
//! deterministic. The generated `pub const` symbol and any manual one live
//! in different modules (e.g. `generated::addresses::GameRuntime__StepFrame`
//! vs `va::STEP_FRAME`), so they don't collide either.

use openwa_re_data::model::{Function, Global};
use openwa_re_data::toml_io::Catalog;
use std::collections::HashSet;
use std::fmt::Write as _;

#[derive(Debug, Default)]
pub struct EmitStats {
    pub functions_emitted: usize,
    pub globals_emitted: usize,
    pub functions_skipped_invalid_ident: usize,
    pub globals_skipped_invalid_ident: usize,
    /// Same TOML name at two different VAs (e.g. MSVC COMDAT-folded CRT
    /// helpers, MFC versioned symbols). The lowest-VA entry keeps the
    /// `pub const`; later occurrences are silently skipped to avoid
    /// duplicate Rust identifiers.
    pub functions_skipped_duplicate_name: usize,
    pub globals_skipped_duplicate_name: usize,
}

pub fn generate(cat: &Catalog) -> (String, EmitStats) {
    let mut out = String::with_capacity(64 * cat.functions.len());
    let mut stats = EmitStats::default();

    write_header(&mut out);

    // Functions: emit in VA order so the generated file diffs cleanly.
    let mut funcs: Vec<&Function> = cat.functions.values().map(|e| &e.value).collect();
    funcs.sort_by_key(|f| f.va);
    let mut seen_fn_names: HashSet<&str> = HashSet::new();
    for f in funcs {
        if !is_valid_rust_ident(&f.name) {
            stats.functions_skipped_invalid_ident += 1;
            continue;
        }
        if !seen_fn_names.insert(f.name.as_str()) {
            stats.functions_skipped_duplicate_name += 1;
            continue;
        }
        write_function(&mut out, f);
        stats.functions_emitted += 1;
    }

    out.push('\n');

    // Globals.
    let mut globals: Vec<&Global> = cat.globals.values().map(|e| &e.value).collect();
    globals.sort_by_key(|g| g.va);
    let mut seen_global_names: HashSet<&str> = HashSet::new();
    for g in globals {
        if !is_valid_rust_ident(&g.name) {
            stats.globals_skipped_invalid_ident += 1;
            continue;
        }
        if !seen_global_names.insert(g.name.as_str()) {
            stats.globals_skipped_duplicate_name += 1;
            continue;
        }
        write_global(&mut out, g);
        stats.globals_emitted += 1;
    }

    (out, stats)
}

fn write_header(out: &mut String) {
    // No inner attributes here — this file is `include!`d into a module
    // body, where inner attrs are disallowed. The enclosing
    // `crates/openwa-game/src/generated/mod.rs` carries the `#![allow]`s.
    out.push_str("// GENERATED by openwa-re-codegen from re/**/*.toml. DO NOT EDIT.\n");
    out.push_str("// Edit the TOML source instead, then rebuild.\n\n");
    out.push_str("use crate::registry::{AddrEntry, AddrKind, AddrSource, CallingConv};\n");
    out.push_str("use crate::inventory;\n\n");
}

fn write_function(out: &mut String, f: &Function) {
    let class = class_prefix(&f.name);
    let calling_conv = function_calling_conv(f);

    writeln!(out, "pub const {}: u32 = 0x{:08X};", f.name, f.va).unwrap();
    out.push_str("inventory::submit! { AddrEntry {\n");
    writeln!(out, "    va: 0x{:08X},", f.va).unwrap();
    writeln!(out, "    name: \"{}\",", f.name).unwrap();
    writeln!(out, "    kind: AddrKind::{},", function_kind(&f.name)).unwrap();
    match calling_conv {
        Some(cc) => writeln!(out, "    calling_conv: Some(CallingConv::{cc}),").unwrap(),
        None => out.push_str("    calling_conv: None,\n"),
    }
    match class {
        Some(c) => writeln!(out, "    class_name: Some(\"{c}\"),").unwrap(),
        None => out.push_str("    class_name: None,\n"),
    }
    out.push_str("    doc: \"\",\n");
    out.push_str("    source: AddrSource::Generated,\n");
    out.push_str("} }\n");
}

fn write_global(out: &mut String, g: &Global) {
    let class = class_prefix(&g.name);
    writeln!(out, "pub const {}: u32 = 0x{:08X};", g.name, g.va).unwrap();
    out.push_str("inventory::submit! { AddrEntry {\n");
    writeln!(out, "    va: 0x{:08X},", g.va).unwrap();
    writeln!(out, "    name: \"{}\",", g.name).unwrap();
    out.push_str("    kind: AddrKind::Global,\n");
    out.push_str("    calling_conv: None,\n");
    match class {
        Some(c) => writeln!(out, "    class_name: Some(\"{c}\"),").unwrap(),
        None => out.push_str("    class_name: None,\n"),
    }
    out.push_str("    doc: \"\",\n");
    out.push_str("    source: AddrSource::Generated,\n");
    out.push_str("} }\n");
}

/// Map TOML calling-convention string + custom_storage flag onto the
/// registry's [`CallingConv`] enum variant name (returned as a `&str` so we
/// can interpolate into the generated source).
///
/// `custom_storage = true` always wins → `Usercall`, regardless of the base
/// convention. Otherwise we use the base.
fn function_calling_conv(f: &Function) -> Option<&'static str> {
    if f.custom_storage {
        return Some("Usercall");
    }
    match f.calling_convention.as_deref()? {
        "__stdcall" => Some("Stdcall"),
        "__cdecl" => Some("Cdecl"),
        "__thiscall" => Some("Thiscall"),
        "__fastcall" => Some("Fastcall"),
        _ => None,
    }
}

/// Constructors get [`AddrKind::Constructor`]; everything else is [`AddrKind::Function`].
/// We can't distinguish vtables/data tables here since they live as `[[global]]`
/// in TOML, and TOML doesn't carry a fine-grained kind for functions either.
fn function_kind(name: &str) -> &'static str {
    if name.ends_with("__Constructor") || name.contains("__Constructor_") {
        "Constructor"
    } else {
        "Function"
    }
}

/// Pull the `Class` prefix out of `Class__rest`. Returns `None` for names
/// without `__` or with a non-identifier prefix.
fn class_prefix(name: &str) -> Option<&str> {
    let idx = name.find("__")?;
    if idx == 0 {
        return None;
    }
    let prefix = &name[..idx];
    if prefix
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '_')
    {
        Some(prefix)
    } else {
        None
    }
}

fn is_valid_rust_ident(s: &str) -> bool {
    let mut chars = s.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first.is_ascii_alphabetic() || first == '_') {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

#[cfg(test)]
mod tests {
    use super::*;
    use openwa_re_data::model::Function;
    use openwa_re_data::toml_io::{Catalog, OwnedEntry};
    use std::path::PathBuf;

    fn fn_(va: u32, name: &str, cc: Option<&str>, custom: bool) -> Function {
        Function {
            va,
            name: name.into(),
            calling_convention: cc.map(str::to_string),
            plate_comment: None,
            no_return: false,
            custom_storage: custom,
            signature: None,
            param: vec![],
            local: vec![],
            comment: vec![],
        }
    }

    fn cat_with(fns: Vec<Function>) -> Catalog {
        let mut c = Catalog::default();
        for f in fns {
            c.functions.insert(
                f.va,
                OwnedEntry {
                    value: f,
                    source: PathBuf::from("<test>"),
                },
            );
        }
        c
    }

    #[test]
    fn emits_function_const_and_inventory_entry() {
        let cat = cat_with(vec![fn_(
            0x004FE070,
            "WorldEntity__TryMovePosition",
            Some("__thiscall"),
            false,
        )]);
        let (out, stats) = generate(&cat);
        assert_eq!(stats.functions_emitted, 1);
        assert!(out.contains("pub const WorldEntity__TryMovePosition: u32 = 0x004FE070;"));
        assert!(out.contains("name: \"WorldEntity__TryMovePosition\","));
        assert!(out.contains("kind: AddrKind::Function,"));
        assert!(out.contains("calling_conv: Some(CallingConv::Thiscall),"));
        assert!(out.contains("class_name: Some(\"WorldEntity\"),"));
        assert!(out.contains("source: AddrSource::Generated,"));
    }

    #[test]
    fn custom_storage_overrides_to_usercall() {
        let cat = cat_with(vec![fn_(
            0x00529F30,
            "GameRuntime__StepFrame",
            Some("__thiscall"),
            true,
        )]);
        let (out, _) = generate(&cat);
        assert!(out.contains("calling_conv: Some(CallingConv::Usercall),"));
    }

    #[test]
    fn constructor_naming_picks_constructor_kind() {
        let cat = cat_with(vec![fn_(
            0x005625A0,
            "BaseEntity__Constructor",
            Some("__stdcall"),
            false,
        )]);
        let (out, _) = generate(&cat);
        assert!(out.contains("kind: AddrKind::Constructor,"));
    }

    #[test]
    fn invalid_ident_is_skipped_not_emitted() {
        let cat = cat_with(vec![fn_(0x500, "0bad_name", Some("__cdecl"), false)]);
        let (out, stats) = generate(&cat);
        assert_eq!(stats.functions_emitted, 0);
        assert_eq!(stats.functions_skipped_invalid_ident, 1);
        assert!(!out.contains("0bad_name"));
    }

    #[test]
    fn duplicate_name_keeps_lowest_va_entry() {
        let cat = cat_with(vec![
            fn_(0x600, "__Stodx", None, false),
            fn_(0x500, "__Stodx", None, false),
        ]);
        let (out, stats) = generate(&cat);
        assert_eq!(stats.functions_emitted, 1);
        assert_eq!(stats.functions_skipped_duplicate_name, 1);
        assert!(out.contains("pub const __Stodx: u32 = 0x00000500;"));
        assert!(!out.contains("0x00000600"));
    }

    #[test]
    fn output_is_va_sorted() {
        let cat = cat_with(vec![
            fn_(0x600, "Z__c", None, false),
            fn_(0x400, "A__a", None, false),
            fn_(0x500, "M__b", None, false),
        ]);
        let (out, _) = generate(&cat);
        let a = out.find("A__a").unwrap();
        let m = out.find("M__b").unwrap();
        let z = out.find("Z__c").unwrap();
        assert!(a < m && m < z, "entries should be VA-sorted in output");
    }
}
