//! Generate hook detours, naked-asm trampolines, and per-hook `install_*`
//! helpers from the merged hook map + RE catalog.
//!
//! Two emission shapes, mirroring `emit_wa_calls`:
//!
//! - **Pure-convention hook** (`custom_storage = false`): the WA function's
//!   ABI matches an `extern "X" fn(...)` signature directly. Codegen emits a
//!   `const _CHECK_*: <expected fn type> = <rust_impl>;` line — a wrong arity
//!   or wrong type is a build-time Rust error pointing at the impl — and a
//!   `pub unsafe fn install_<wa_function>() -> Result<(), String>` that calls
//!   `crate::hook::install(...)` with `rust_impl as *const ()`.
//!
//! - **Usercall hook** (`custom_storage = true`): WA caller passes some args
//!   in registers (ESI/EAX/EDI/…) or at non-default stack slots. Codegen
//!   emits a `#[unsafe(naked)] extern "C" fn tramp_<wa_function>()` whose
//!   body is a `naked_asm!` block that:
//!
//!     1. saves `EDX` (baseline; cdecl may clobber but WA `__usercall` may not)
//!        plus any `preserve_registers` (in declaration order),
//!     2. pushes stack-stored params in reverse-offset order so they land in
//!        ascending Rust-cdecl arg order on the impl side,
//!     3. pushes register-stored params in reverse declaration order,
//!     4. `call`s the cdecl impl,
//!     5. `add esp, N` to drop the pushed args,
//!     6. restores preserved regs in reverse, then `pop edx`,
//!     7. `ret imm16` cleans the WA caller's stack args per the WA convention
//!        (stdcall/thiscall/fastcall: `imm16 = stack_param_count * 4`;
//!        cdecl: plain `ret`).
//!
//!   The `_CHECK_*` const is also emitted with the impl's expected cdecl
//!   signature (register-params first, then stack-params, in declaration
//!   order — matching the macro convention in `crates/openwa-dll/src/hook.rs`).
//!
//! In both shapes, when `save_original = true` codegen also emits:
//!   - `static ORIG_<wa_function>: AtomicU32 = AtomicU32::new(0);`
//!   - `pub unsafe fn call_original_<wa_function>(...)` — typed call-through
//!     that transmutes the atomic to a typed `extern "X" fn(...)` and forwards.
//!   - The `install_<wa_function>` function stores MinHook's returned
//!     trampoline pointer into `ORIG_*` (via `install_generated`).

use openwa_re_data::model::{Function, Param};
use openwa_re_data::toml_io::Catalog;
use std::fmt::Write as _;

use crate::hook_map::{HookEntry, HookMap};
use crate::storage::{Reg, Storage};
use crate::type_resolver::parse_type_ref;

#[derive(Debug, Default)]
pub struct EmitStats {
    pub emitted_default_storage: usize,
    pub emitted_custom_storage: usize,
    /// Hook lists a `wa_function` that has no matching `[[function]]` entry
    /// in the catalog. Build-time hard error — hooks aren't best-effort.
    pub missing_in_catalog: Vec<String>,
    /// Hook function has no calling convention annotated in TOML.
    pub missing_convention: Vec<String>,
    /// `custom_storage = true` but some param has no `storage =`.
    pub missing_storage: Vec<String>,
    /// Some param uses an unsupported register or storage form.
    pub invalid_storage: Vec<String>,
}

impl EmitStats {
    pub fn emitted(&self) -> usize {
        self.emitted_default_storage + self.emitted_custom_storage
    }
}

/// Generate a single Rust source file: detour signature checks, trampolines,
/// `ORIG_*` atomics, `call_original_*` helpers, and per-hook `install_*`
/// functions. Top-level layout:
///
/// ```ignore
/// // GENERATED by openwa-re-codegen. DO NOT EDIT.
/// use core::sync::atomic::{AtomicU32, Ordering};
///
/// pub mod hooks {
///     // one section per hook, sorted by wa_function for stable diffs
///     // ...
/// }
/// ```
pub fn generate(cat: &Catalog, hook_map: &HookMap) -> (String, EmitStats) {
    let mut stats = EmitStats::default();
    let mut out = String::with_capacity(2048);

    out.push_str("// GENERATED by openwa-re-codegen. DO NOT EDIT.\n");
    out.push_str(
        "// Source: crates/openwa-dll/hooks/*.toml + re/**/*.toml + rust_path mappings.\n\n",
    );
    out.push_str("use core::sync::atomic::{AtomicU32, Ordering};\n\n");
    out.push_str("pub mod hooks {\n");
    out.push_str("    #[allow(unused_imports)]\n");
    out.push_str("    use super::{AtomicU32, Ordering};\n\n");

    // Stable, alphabetical emission order — purely cosmetic, but it makes the
    // generated file diff cleanly when one hook is added or removed.
    let mut keys: Vec<&str> = hook_map.hooks.keys().map(String::as_str).collect();
    keys.sort();

    for key in keys {
        let owned = &hook_map.hooks[key];
        let hook = &owned.value;

        let Some(func_entry) = cat
            .functions
            .values()
            .find(|e| e.value.name == hook.wa_function)
        else {
            stats.missing_in_catalog.push(hook.wa_function.clone());
            continue;
        };
        let func = &func_entry.value;

        if func.calling_convention.is_none() {
            stats.missing_convention.push(hook.wa_function.clone());
            continue;
        }

        match emit_hook(&mut out, cat, hook, func) {
            Ok(EmittedKind::DefaultStorage) => stats.emitted_default_storage += 1,
            Ok(EmittedKind::CustomStorage) => stats.emitted_custom_storage += 1,
            Err(EmitError::MissingStorage) => stats.missing_storage.push(hook.wa_function.clone()),
            Err(EmitError::InvalidStorage(reason)) => stats
                .invalid_storage
                .push(format!("{}: {reason}", hook.wa_function)),
        }
    }

    out.push_str("} // mod hooks\n");
    (out, stats)
}

enum EmittedKind {
    DefaultStorage,
    CustomStorage,
}

enum EmitError {
    MissingStorage,
    InvalidStorage(String),
}

fn emit_hook(
    out: &mut String,
    cat: &Catalog,
    hook: &HookEntry,
    func: &Function,
) -> Result<EmittedKind, EmitError> {
    let cc_kw = match func.calling_convention.as_deref().unwrap_or("") {
        "__stdcall" => "stdcall",
        "__cdecl" => "cdecl",
        "__thiscall" => "thiscall",
        "__fastcall" => "fastcall",
        other => return Err(EmitError::InvalidStorage(format!("convention {other:?}"))),
    };

    // Resolve every param + return type. If anything is unresolved the hook
    // is broken at the TOML level — surface as InvalidStorage so the build
    // fails noisily rather than silently skipping. (Distinct from wa_calls,
    // which is best-effort.)
    let params = resolve_params(cat, &func.param)?;
    let ret = resolve_return(cat, func)?;

    let wa = &hook.wa_function;

    writeln!(out, "    // ── {wa} ──").unwrap();

    if func.custom_storage {
        emit_custom_storage(out, hook, func, cc_kw, &params, &ret)?;
        Ok(EmittedKind::CustomStorage)
    } else {
        emit_default_storage(out, hook, func, cc_kw, &params, &ret)?;
        Ok(EmittedKind::DefaultStorage)
    }
}

/// Pure-convention hook: no trampoline. Just a `const _CHECK_*` typed against
/// the WA convention and a one-line `install_*` that points MinHook at the
/// impl directly.
fn emit_default_storage(
    out: &mut String,
    hook: &HookEntry,
    func: &Function,
    cc_kw: &str,
    params: &[(String, String)],
    ret: &Option<String>,
) -> Result<(), EmitError> {
    let wa = &hook.wa_function;
    let arg_types = params
        .iter()
        .map(|(_, t)| t.as_str())
        .collect::<Vec<_>>()
        .join(", ");
    let ret_suffix = match ret {
        Some(r) => format!(" -> {r}"),
        None => String::new(),
    };

    // Detour signature check — wrong impl signature errors here at build time.
    writeln!(out, "    #[allow(non_upper_case_globals, dead_code)]").unwrap();
    writeln!(
        out,
        "    const _CHECK_{wa}: unsafe extern \"{cc_kw}\" fn({arg_types}){ret_suffix} = {};",
        hook.rust_impl,
    )
    .unwrap();

    if hook.save_original {
        emit_orig_atomic_and_call_through(out, wa, cc_kw, params, ret);
    }

    emit_install_fn(out, hook, func, /*detour_is_trampoline=*/ false);
    writeln!(out).unwrap();
    Ok(())
}

/// Usercall hook: trampoline reads params from the WA caller's frame into
/// cdecl arg order, then forwards to the impl.
fn emit_custom_storage(
    out: &mut String,
    hook: &HookEntry,
    func: &Function,
    cc_kw: &str,
    params: &[(String, String)],
    ret: &Option<String>,
) -> Result<(), EmitError> {
    // Parse storage on every param; usercall must declare them all.
    let mut reg_params: Vec<(usize, Reg)> = Vec::new();
    let mut stack_params: Vec<(usize, u32)> = Vec::new(); // (param_idx, byte_offset)
    for (i, p) in func.param.iter().enumerate() {
        let s = p.storage.as_deref().ok_or(EmitError::MissingStorage)?;
        let parsed = crate::storage::parse(s)
            .map_err(|e| EmitError::InvalidStorage(format!("param {}: {e}", p.name)))?;
        match parsed {
            Storage::Register(r) => reg_params.push((i, r)),
            Storage::Stack { offset, .. } => stack_params.push((i, offset)),
            Storage::Pair(_, _) => {
                return Err(EmitError::InvalidStorage(format!(
                    "param {} uses register pair (unsupported)",
                    p.name
                )));
            }
        }
    }

    // Resolve `preserve_registers`. Overlap with a param-input register is
    // legal: the input register is pushed first (for the post-call restore)
    // and again later as the cdecl call arg — the register's live value
    // survives both pushes, and the trailing `pop` restores it after the
    // impl returns. Used by thiscall hooks (`preserve_registers = ["ecx"]`)
    // where MSVC callers loop without re-setting ECX between calls.
    let preserve: Vec<Reg> = hook
        .preserve_registers
        .resolved()
        .into_iter()
        .map(|s| {
            Reg::parse(&s).ok_or_else(|| {
                EmitError::InvalidStorage(format!("preserve_registers: unknown reg {s:?}"))
            })
        })
        .collect::<Result<_, _>>()?;

    // Sort stack params by offset ascending. They get pushed in reverse so
    // the lowest-offset one ends up at the lowest address in the impl's
    // cdecl frame (matching the impl's first-stack-param slot).
    stack_params.sort_by_key(|(_, off)| *off);

    let wa = &hook.wa_function;

    // Impl signature ordering: reg params (in declaration order), then stack
    // params (in declaration / sorted-by-offset order).
    let impl_param_order: Vec<usize> = reg_params
        .iter()
        .map(|(i, _)| *i)
        .chain(stack_params.iter().map(|(i, _)| *i))
        .collect();
    let impl_types: Vec<&str> = impl_param_order
        .iter()
        .map(|i| params[*i].1.as_str())
        .collect();
    let impl_arg_types = impl_types.join(", ");
    let ret_suffix = match ret {
        Some(r) => format!(" -> {r}"),
        None => String::new(),
    };

    // Detour signature check pointed at the cdecl impl.
    writeln!(out, "    #[allow(non_upper_case_globals, dead_code)]").unwrap();
    writeln!(
        out,
        "    const _CHECK_{wa}: unsafe extern \"cdecl\" fn({impl_arg_types}){ret_suffix} = {};",
        hook.rust_impl,
    )
    .unwrap();

    // ── Naked trampoline ──
    //
    // Stack frame walkthrough on entry from WA.exe:
    //   [esp+0]   = return address into WA caller
    //   [esp+4]   = first WA stack arg
    //   [esp+8]   = second WA stack arg
    //   ...
    //
    // After `push edx` + `push <preserve_i>` ... pushes, slots shift by
    // 4 * (1 + preserve.len()). We track this as `saved_bytes`.
    writeln!(out, "    #[unsafe(naked)]").unwrap();
    writeln!(out, "    pub unsafe extern \"cdecl\" fn tramp_{wa}() {{").unwrap();
    writeln!(out, "        core::arch::naked_asm!(").unwrap();

    // 1. baseline EDX save.
    writeln!(out, "            \"push edx\",").unwrap();
    // 2. extra preserves in declaration order. (Skip "edx" if explicitly
    //    listed — already saved.)
    let extra_preserves: Vec<Reg> = preserve
        .iter()
        .copied()
        .filter(|r| *r != Reg::Edx)
        .collect();
    for r in &extra_preserves {
        writeln!(out, "            \"push {}\",", r.asm_name()).unwrap();
    }
    let saved_count = 1 + extra_preserves.len() as u32; // edx + extras
    let saved_bytes = saved_count * 4;

    // 3. stack args, reverse-offset order. Each prior push shifts the source
    //    offset by 4, but the source offset itself stays at [esp+OLD+pushed*4].
    let mut pushed: u32 = 0;
    for (_i, off) in stack_params.iter().rev() {
        let source_off = saved_bytes + off + pushed * 4;
        writeln!(
            out,
            "            \"push DWORD PTR [esp+{source_off}]\",",
            source_off = source_off,
        )
        .unwrap();
        pushed += 1;
    }
    // 4. register args, reverse declaration order.
    for (_i, r) in reg_params.iter().rev() {
        writeln!(out, "            \"push {}\",", r.asm_name()).unwrap();
        pushed += 1;
    }

    // 5. call. Emit a literal `"call {impl_fn}",` line — the doubled braces
    //    here become single braces in the generated source, where they bind
    //    the `impl_fn = sym <rust_impl>` template parameter below.
    writeln!(out, "            \"call {{impl_fn}}\",").unwrap();

    // 6. clean cdecl args we pushed.
    if pushed > 0 {
        writeln!(out, "            \"add esp, {}\",", pushed * 4).unwrap();
    }

    // 7. restore preserves in reverse, then edx.
    for r in extra_preserves.iter().rev() {
        writeln!(out, "            \"pop {}\",", r.asm_name()).unwrap();
    }
    writeln!(out, "            \"pop edx\",").unwrap();

    // 8. return to WA caller; clean stack args per WA convention.
    let wa_stack_bytes = stack_params.len() as u32 * 4;
    if cc_kw == "cdecl" || wa_stack_bytes == 0 {
        writeln!(out, "            \"ret\",").unwrap();
    } else {
        writeln!(out, "            \"ret {}\",", wa_stack_bytes).unwrap();
    }

    writeln!(out, "            impl_fn = sym {},", hook.rust_impl).unwrap();
    writeln!(out, "        )").unwrap();
    writeln!(out, "    }}").unwrap();

    if hook.save_original {
        emit_orig_atomic_and_call_through(out, wa, cc_kw, params, ret);
    }

    emit_install_fn(out, hook, func, /*detour_is_trampoline=*/ true);
    writeln!(out).unwrap();
    Ok(())
}

fn emit_orig_atomic_and_call_through(
    out: &mut String,
    wa: &str,
    cc_kw: &str,
    params: &[(String, String)],
    ret: &Option<String>,
) {
    let arg_decl = params
        .iter()
        .map(|(n, t)| format!("{n}: {t}"))
        .collect::<Vec<_>>()
        .join(", ");
    let arg_types = params
        .iter()
        .map(|(_, t)| t.as_str())
        .collect::<Vec<_>>()
        .join(", ");
    let arg_call = params
        .iter()
        .map(|(n, _)| n.as_str())
        .collect::<Vec<_>>()
        .join(", ");
    let ret_suffix = match ret {
        Some(r) => format!(" -> {r}"),
        None => String::new(),
    };
    writeln!(
        out,
        "    pub static ORIG_{wa}: AtomicU32 = AtomicU32::new(0);"
    )
    .unwrap();
    writeln!(
        out,
        "    #[inline]\n    pub unsafe fn call_original_{wa}({arg_decl}){ret_suffix} {{",
    )
    .unwrap();
    writeln!(out, "        unsafe {{").unwrap();
    writeln!(
        out,
        "            let p = ORIG_{wa}.load(Ordering::Relaxed);",
    )
    .unwrap();
    writeln!(
        out,
        "            let f: unsafe extern \"{cc_kw}\" fn({arg_types}){ret_suffix} = core::mem::transmute(p);",
    )
    .unwrap();
    writeln!(out, "            f({arg_call})").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
}

fn emit_install_fn(
    out: &mut String,
    hook: &HookEntry,
    func: &Function,
    detour_is_trampoline: bool,
) {
    let wa = &hook.wa_function;
    let detour_expr = if detour_is_trampoline {
        format!("tramp_{wa} as *const ()")
    } else {
        format!("{} as *const ()", hook.rust_impl)
    };
    writeln!(
        out,
        "    pub unsafe fn install_{wa}() -> Result<(), String> {{"
    )
    .unwrap();
    writeln!(out, "        unsafe {{").unwrap();
    if hook.save_original {
        writeln!(
            out,
            "            let trampoline = crate::hook::install({wa:?}, openwa_game::generated::addresses::{wa}, {detour_expr})?;",
        )
        .unwrap();
        writeln!(
            out,
            "            ORIG_{wa}.store(trampoline as u32, Ordering::Relaxed);",
        )
        .unwrap();
        writeln!(out, "            Ok(())").unwrap();
    } else {
        writeln!(
            out,
            "            crate::hook::install({wa:?}, openwa_game::generated::addresses::{wa}, {detour_expr})?;",
        )
        .unwrap();
        writeln!(out, "            Ok(())").unwrap();
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    let _ = func;
}

fn resolve_params(cat: &Catalog, params: &[Param]) -> Result<Vec<(String, String)>, EmitError> {
    let mut out = Vec::with_capacity(params.len());
    for (i, p) in params.iter().enumerate() {
        let ty = parse_type_ref(&p.ty, cat).render().map_err(|_| {
            EmitError::InvalidStorage(format!("unresolved type for param {}: {:?}", p.name, p.ty))
        })?;
        let name = sanitise_param_name(&p.name, i);
        out.push((name, ty));
    }
    Ok(out)
}

fn resolve_return(cat: &Catalog, func: &Function) -> Result<Option<String>, EmitError> {
    let Some(sig) = &func.signature else {
        return Err(EmitError::InvalidStorage("no [function.signature]".into()));
    };
    let rendered = parse_type_ref(&sig.returns, cat)
        .render()
        .map_err(|_| EmitError::InvalidStorage(format!("unresolved return {:?}", sig.returns)))?;
    Ok(if rendered == "core::ffi::c_void" {
        None
    } else {
        Some(rendered)
    })
}

fn sanitise_param_name(name: &str, idx: usize) -> String {
    let mut chars = name.chars();
    let first = match chars.next() {
        Some(c) => c,
        None => return format!("arg{idx}"),
    };
    if !(first.is_ascii_alphabetic() || first == '_') {
        return format!("arg{idx}");
    }
    if !chars.all(|c| c.is_ascii_alphanumeric() || c == '_') {
        return format!("arg{idx}");
    }
    if is_rust_keyword(name) || matches!(name, "f" | "trampoline" | "p") {
        return format!("arg{idx}");
    }
    name.to_string()
}

fn is_rust_keyword(s: &str) -> bool {
    matches!(
        s,
        "as" | "async"
            | "await"
            | "break"
            | "const"
            | "continue"
            | "crate"
            | "dyn"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "yield"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::hook_map::{HookEntry, HookMap, OwnedHook, PreserveSpec};
    use openwa_re_data::model::{Function, Param, Signature, Struct};
    use openwa_re_data::toml_io::{Catalog, OwnedEntry};
    use std::path::PathBuf;

    fn fn_with(
        va: u32,
        name: &str,
        cc: Option<&str>,
        custom: bool,
        ret: Option<&str>,
        params: Vec<(&str, &str, Option<&str>)>,
    ) -> Function {
        Function {
            va,
            name: name.into(),
            calling_convention: cc.map(str::to_string),
            plate_comment: None,
            no_return: false,
            custom_storage: custom,
            signature: ret.map(|r| Signature {
                returns: r.into(),
                return_storage: None,
            }),
            param: params
                .into_iter()
                .map(|(n, t, s)| Param {
                    name: n.into(),
                    ty: t.into(),
                    storage: s.map(str::to_string),
                })
                .collect(),
            local: vec![],
            comment: vec![],
        }
    }

    fn cat_with(fns: Vec<Function>) -> Catalog {
        let mut c = Catalog::default();
        for f in fns {
            c.functions.insert(
                f.va,
                OwnedEntry {
                    value: f,
                    source: PathBuf::from("<test>"),
                },
            );
        }
        c
    }

    fn with_struct(cat: &mut Catalog, name: &str, rust_path: &str) {
        cat.structs.insert(
            name.into(),
            OwnedEntry {
                value: Struct {
                    name: name.into(),
                    namespace: None,
                    size: 0,
                    plate_comment: None,
                    rust_path: Some(rust_path.into()),
                    field: vec![],
                },
                source: PathBuf::from("<test>"),
            },
        );
    }

    fn hook_map_with(hooks: Vec<HookEntry>) -> HookMap {
        let mut m = HookMap::default();
        for h in hooks {
            m.hooks.insert(
                h.wa_function.clone(),
                OwnedHook {
                    value: h,
                    source: PathBuf::from("<test>"),
                },
            );
        }
        m
    }

    #[test]
    fn pure_thiscall_hook_emits_check_and_install() {
        let mut cat = cat_with(vec![fn_with(
            0x005261E0,
            "IsSoundSuppressed",
            Some("__thiscall"),
            false,
            Some("uint"),
            vec![("this", "GameWorld *", None)],
        )]);
        with_struct(&mut cat, "GameWorld", "openwa_game::engine::GameWorld");
        let map = hook_map_with(vec![HookEntry {
            wa_function: "IsSoundSuppressed".into(),
            rust_impl: "crate::replacements::sound::is_sound_suppressed_detour".into(),
            save_original: false,
            preserve_registers: PreserveSpec::None,
        }]);
        let (out, stats) = generate(&cat, &map);
        assert_eq!(stats.emitted_default_storage, 1);
        assert!(stats.missing_in_catalog.is_empty());
        assert!(out.contains("const _CHECK_IsSoundSuppressed: unsafe extern \"thiscall\" fn(*mut openwa_game::engine::GameWorld) -> u32"));
        assert!(out.contains("= crate::replacements::sound::is_sound_suppressed_detour;",));
        assert!(out.contains("pub unsafe fn install_IsSoundSuppressed()"));
        assert!(out.contains(
            "crate::hook::install(\"IsSoundSuppressed\", openwa_game::generated::addresses::IsSoundSuppressed",
        ));
    }

    #[test]
    fn usercall_with_single_reg_no_stack_emits_trampoline() {
        // Mirror of `GameRuntime__InitFrameDelay`: usercall(EAX=this), no
        // stack params, plain RET, __cdecl base + custom_storage.
        let mut cat = cat_with(vec![fn_with(
            0x0052CAF0,
            "GameRuntime__InitFrameDelay",
            Some("__cdecl"),
            true,
            Some("void"),
            vec![("this", "void *", Some("EAX"))],
        )]);
        let _ = &mut cat; // no rust_path needed; void * resolves directly
        let map = hook_map_with(vec![HookEntry {
            wa_function: "GameRuntime__InitFrameDelay".into(),
            rust_impl: "openwa_game::engine::main_loop::dispatch_frame::init_frame_delay_impl"
                .into(),
            save_original: false,
            preserve_registers: PreserveSpec::None,
        }]);
        let (out, stats) = generate(&cat, &map);
        assert_eq!(stats.emitted_custom_storage, 1);
        assert!(
            out.contains(
                "const _CHECK_GameRuntime__InitFrameDelay: unsafe extern \"cdecl\" fn(*mut core::ffi::c_void)"
            ),
            "got:\n{out}",
        );
        assert!(out.contains("pub unsafe extern \"cdecl\" fn tramp_GameRuntime__InitFrameDelay()"));
        assert!(out.contains("\"push edx\","));
        assert!(out.contains("\"push eax\","));
        // No extra stack args, no `add esp` would still be present for the
        // single register push.
        assert!(out.contains("\"add esp, 4\","));
        assert!(out.contains("\"pop edx\","));
        // cdecl base → plain ret (caller cleans).
        assert!(out.contains("\"ret\","));
        assert!(!out.contains("\"ret 0\","));
        assert!(out.contains(
            "impl_fn = sym openwa_game::engine::main_loop::dispatch_frame::init_frame_delay_impl,"
        ));
    }

    #[test]
    fn usercall_with_reg_and_stack_pushes_in_correct_order() {
        // Synthetic: ESI=worm, plus 2 stack params at 0x4 and 0x8. stdcall
        // base, RET 0x8. Mirrors PlayWormSound (0x5150D0).
        let cat = cat_with(vec![fn_with(
            0x005150D0,
            "PlayWormSound",
            Some("__stdcall"),
            true,
            Some("void"),
            vec![
                ("worm", "void *", Some("EDI")),
                ("sound_id", "uint", Some("stack:0x4")),
                ("volume", "int", Some("stack:0x8")),
            ],
        )]);
        let map = hook_map_with(vec![HookEntry {
            wa_function: "PlayWormSound".into(),
            rust_impl: "crate::replacements::sound::play_worm_sound_cdecl".into(),
            save_original: false,
            preserve_registers: PreserveSpec::None,
        }]);
        let (out, stats) = generate(&cat, &map);
        assert_eq!(stats.emitted_custom_storage, 1);
        // Push order at the call site (with saved_bytes=4 from `push edx`):
        //   1. push DWORD PTR [esp+12]  (was [esp+8] before edx, +4 = +12)
        //   2. push DWORD PTR [esp+12]  (was [esp+4], then +4 (edx) + 4 (prior push) = 12 again)
        //   3. push edi                  (the EDI reg input)
        // Total pushed = 12 bytes → add esp, 12 after call.
        assert!(out.contains("\"push DWORD PTR [esp+12]\","));
        assert!(out.contains("\"push edi\","));
        assert!(out.contains("\"add esp, 12\","));
        // stdcall WA → ret 8 cleans the WA-side stack args.
        assert!(out.contains("\"ret 8\","));
    }

    #[test]
    fn preserve_registers_emits_push_pop_pairs() {
        let cat = cat_with(vec![fn_with(
            0x00500000,
            "Foo__bar",
            Some("__stdcall"),
            true,
            Some("void"),
            vec![("this", "void *", Some("EAX"))],
        )]);
        let map = hook_map_with(vec![HookEntry {
            wa_function: "Foo__bar".into(),
            rust_impl: "crate::x::bar_impl".into(),
            save_original: false,
            preserve_registers: PreserveSpec::List(vec!["ecx".into()]),
        }]);
        let (out, _) = generate(&cat, &map);
        // After `push edx`, `push ecx`, the EAX read sits at [esp+...] — but
        // here EAX is a *direct* reg input, not a stack read, so no offset
        // shift matters. We just verify the preserve pair is present.
        let push_ecx = out.find("\"push ecx\",").expect("push ecx");
        let pop_ecx = out.find("\"pop ecx\",").expect("pop ecx");
        assert!(push_ecx < pop_ecx);
    }

    #[test]
    fn preserve_overlap_with_input_is_allowed() {
        // ECX appears as both a param-input register and a preserve target.
        // The trampoline pushes ECX twice (once for restore-after-call, once
        // as the cdecl call arg) — the register's live value survives both
        // pushes, and the trailing `pop ecx` restores it.
        let cat = cat_with(vec![fn_with(
            0x00500000,
            "Foo__bar",
            Some("__thiscall"),
            true,
            Some("int"),
            vec![
                ("this", "void *", Some("ECX")),
                ("key", "int", Some("stack:0x4")),
            ],
        )]);
        let map = hook_map_with(vec![HookEntry {
            wa_function: "Foo__bar".into(),
            rust_impl: "crate::x::bar_impl".into(),
            save_original: false,
            preserve_registers: PreserveSpec::List(vec!["ecx".into()]),
        }]);
        let (out, stats) = generate(&cat, &map);
        assert_eq!(stats.emitted_custom_storage, 1);
        assert!(stats.invalid_storage.is_empty());
        // Two `push ecx` instructions: one for the preserve save, one for
        // the cdecl call arg. Followed by one `pop ecx` to restore.
        assert_eq!(out.matches("\"push ecx\",").count(), 2);
        assert_eq!(out.matches("\"pop ecx\",").count(), 1);
    }

    #[test]
    fn save_original_emits_atomic_and_call_through() {
        let mut cat = cat_with(vec![fn_with(
            0x005261E0,
            "IsSoundSuppressed",
            Some("__thiscall"),
            false,
            Some("uint"),
            vec![("this", "GameWorld *", None)],
        )]);
        with_struct(&mut cat, "GameWorld", "openwa_game::engine::GameWorld");
        let map = hook_map_with(vec![HookEntry {
            wa_function: "IsSoundSuppressed".into(),
            rust_impl: "crate::replacements::sound::is_sound_suppressed_detour".into(),
            save_original: true,
            preserve_registers: PreserveSpec::None,
        }]);
        let (out, _) = generate(&cat, &map);
        assert!(out.contains("pub static ORIG_IsSoundSuppressed: AtomicU32"));
        assert!(out.contains("pub unsafe fn call_original_IsSoundSuppressed("));
        assert!(out.contains("ORIG_IsSoundSuppressed.store(trampoline as u32, Ordering::Relaxed)"));
    }

    #[test]
    fn missing_function_in_catalog_is_recorded() {
        let cat = Catalog::default();
        let map = hook_map_with(vec![HookEntry {
            wa_function: "NonExistent__foo".into(),
            rust_impl: "x::y".into(),
            save_original: false,
            preserve_registers: PreserveSpec::None,
        }]);
        let (_, stats) = generate(&cat, &map);
        assert_eq!(stats.missing_in_catalog, vec!["NonExistent__foo"]);
    }
}
