//! Generate typed `unsafe fn` wrappers for calling WA.exe functions from Rust.
//!
//! **Path A only** (custom_storage = false + one of the four base conventions):
//! the body is a pointer transmute of `rb(va::Name)` to a typed
//! `unsafe extern "X" fn(...)`. No asm, no manual register shuffling — the
//! Rust ABI side handles register/stack allocation correctly because the
//! function's storage is the convention's default.
//!
//! Functions with `custom_storage = true` (i.e. usercall — register-passed
//! params not at convention-default positions) need a Path B asm-based body,
//! which is a separate emitter. They're tracked here as `skipped_usercall`.
//!
//! Functions get skipped without emission when:
//!   - calling convention is missing or unrecognised
//!   - return type is missing (no `[function.signature]`)
//!   - any param type or the return type can't be resolved (Unresolved →
//!     missing `rust_path` on a struct/enum/typedef)
//!   - the TOML name doesn't parse as `Class__member` (free functions
//!     without a class prefix land in the `free` submodule instead)
//!
//! Output is grouped by class:
//!
//! ```ignore
//! pub mod wa_calls {
//!     pub mod GameRuntime {
//!         #[inline]
//!         pub unsafe fn StepFrame(
//!             this: *mut openwa_game::engine::runtime::GameRuntime,
//!             frame: i32,
//!         ) -> i32 { /* … */ }
//!     }
//!     pub mod free { /* unclassified */ }
//! }
//! ```

use openwa_re_data::model::{Function, Param, Signature};
use openwa_re_data::toml_io::Catalog;
use std::collections::{BTreeMap, HashSet};
use std::fmt::Write as _;

use crate::type_resolver::parse_type_ref;

/// Per-run statistics. `skipped_*` counts are non-fatal — they exist so the
/// build script can print a one-line summary and so unit tests can assert
/// expected coverage.
#[derive(Debug, Default)]
pub struct EmitStats {
    pub functions_emitted: usize,
    pub skipped_no_convention: usize,
    pub skipped_unknown_convention: usize,
    pub skipped_usercall: usize,
    pub skipped_no_return_type: usize,
    pub skipped_unresolved_type: usize,
    pub skipped_invalid_member_ident: usize,
    /// `Class__member` collision (rare; e.g. two TOML entries with the same
    /// Class+member at different VAs). Lowest-VA wins.
    pub skipped_duplicate_member: usize,
}

pub fn generate(cat: &Catalog) -> (String, EmitStats) {
    let mut out = String::with_capacity(128 * cat.functions.len());
    let mut stats = EmitStats::default();

    write_header(&mut out);

    // Group functions by class (or `free` for unclassified).
    //
    // BTreeMap → deterministic alphabetical class order. Within a class, sort
    // by VA so the file diffs cleanly when a function moves but its class
    // doesn't.
    let mut by_class: BTreeMap<String, Vec<&Function>> = BTreeMap::new();
    let mut funcs: Vec<&Function> = cat.functions.values().map(|e| &e.value).collect();
    funcs.sort_by_key(|f| f.va);
    for f in funcs {
        let class = class_prefix(&f.name).unwrap_or("free").to_string();
        by_class.entry(class).or_default().push(f);
    }

    out.push_str("pub mod wa_calls {\n");
    for (class, members) in &by_class {
        write_class_module(&mut out, cat, class, members, &mut stats);
    }
    out.push_str("} // mod wa_calls\n");

    (out, stats)
}

fn write_header(out: &mut String) {
    // No inner attributes — `include!` doesn't allow them; the enclosing
    // `src/generated/mod.rs` carries the `#![allow]`s.
    out.push_str("// GENERATED by openwa-re-codegen. DO NOT EDIT.\n");
    out.push_str(
        "// Source: re/**/*.toml + rust_path mappings on struct/enum/typedef entries.\n\n",
    );
}

fn write_class_module(
    out: &mut String,
    cat: &Catalog,
    class: &str,
    members: &[&Function],
    stats: &mut EmitStats,
) {
    // Buffer this class's content so we can skip the whole module if every
    // member gets filtered out (otherwise we emit `pub mod Foo {}` with
    // nothing in it — harmless but noisy in the generated file).
    let mut body = String::new();
    let mut seen_members: HashSet<&str> = HashSet::new();
    let mut emitted_any = false;

    for f in members {
        let member = member_part(&f.name).unwrap_or(f.name.as_str());

        // Skip filters — order matters for stat attribution (most specific first).
        if f.custom_storage {
            stats.skipped_usercall += 1;
            continue;
        }
        let Some(cc_kw) = base_calling_convention(f) else {
            if f.calling_convention.is_none() {
                stats.skipped_no_convention += 1;
            } else {
                stats.skipped_unknown_convention += 1;
            }
            continue;
        };
        let Some(signature) = f.signature.as_ref() else {
            stats.skipped_no_return_type += 1;
            continue;
        };
        if !is_valid_rust_ident(member) {
            stats.skipped_invalid_member_ident += 1;
            continue;
        }
        if !seen_members.insert(member) {
            stats.skipped_duplicate_member += 1;
            continue;
        }

        // Resolve every type. Bail to skipped_unresolved_type on first miss
        // — recording exactly which type is unresolved is the job of a
        // separate audit log (TODO when the skipped count gets noisy).
        let Some(resolved_params) = resolve_params(cat, &f.param) else {
            stats.skipped_unresolved_type += 1;
            continue;
        };
        let Some(resolved_ret) = resolve_return(cat, signature) else {
            stats.skipped_unresolved_type += 1;
            continue;
        };

        write_wrapper(&mut body, f, member, cc_kw, &resolved_params, &resolved_ret);
        stats.functions_emitted += 1;
        emitted_any = true;
    }

    if !emitted_any {
        return;
    }
    writeln!(out, "    #[allow(non_snake_case)]").unwrap();
    writeln!(out, "    pub mod {class} {{").unwrap();
    out.push_str(&body);
    writeln!(out, "    }} // mod {class}").unwrap();
}

/// Each wrapper:
///
/// ```ignore
/// #[inline]
/// pub unsafe fn Member(arg1: T1, arg2: T2) -> R {
///     let f: unsafe extern "<conv>" fn(T1, T2) -> R =
///         core::mem::transmute(
///             crate::rebase::rb(crate::generated::addresses::<TomlName>),
///         );
///     f(arg1, arg2)
/// }
/// ```
///
/// `R` is omitted when the return type renders as `core::ffi::c_void` (TOML
/// `returns = "void"`) — Rust's empty return is implicit.
fn write_wrapper(
    out: &mut String,
    f: &Function,
    member: &str,
    cc_kw: &str,
    params: &[(String, String)], // (name, rendered type)
    ret: &Option<String>,        // None ↔ void
) {
    // Pretty-print signatures only when they're long enough to warrant wrapping.
    let sig_args = params
        .iter()
        .map(|(n, t)| format!("{n}: {t}"))
        .collect::<Vec<_>>()
        .join(", ");
    let ret_suffix = match ret {
        Some(r) => format!(" -> {r}"),
        None => String::new(),
    };
    let fn_arg_types = params
        .iter()
        .map(|(_, t)| t.as_str())
        .collect::<Vec<_>>()
        .join(", ");
    let call_args = params
        .iter()
        .map(|(n, _)| n.as_str())
        .collect::<Vec<_>>()
        .join(", ");

    // Rust 2024 edition: `unsafe fn` no longer makes its body implicitly
    // unsafe, so we explicitly wrap the transmute + call in `unsafe { … }`.
    writeln!(out, "        #[inline]").unwrap();
    writeln!(
        out,
        "        pub unsafe fn {member}({sig_args}){ret_suffix} {{",
    )
    .unwrap();
    writeln!(out, "            unsafe {{").unwrap();
    writeln!(
        out,
        "                let f: unsafe extern \"{cc_kw}\" fn({fn_arg_types}){ret_suffix} =",
    )
    .unwrap();
    writeln!(
        out,
        "                    core::mem::transmute(crate::rebase::rb(crate::generated::addresses::{}));",
        f.name,
    )
    .unwrap();
    writeln!(out, "                f({call_args})").unwrap();
    writeln!(out, "            }}").unwrap();
    writeln!(out, "        }}").unwrap();
}

fn resolve_params(cat: &Catalog, params: &[Param]) -> Option<Vec<(String, String)>> {
    let mut out = Vec::with_capacity(params.len());
    for (i, p) in params.iter().enumerate() {
        let ty = parse_type_ref(&p.ty, cat).render().ok()?;
        // Sanitise the param name — TOML allows raw C identifiers; we need
        // valid Rust idents that don't shadow our local `f` and aren't Rust
        // reserved keywords (`self`, `type`, `match`, …). Fall back to
        // `arg<i>` when any of those rules fire.
        let name = if !is_valid_rust_ident(&p.name) || p.name == "f" || is_rust_keyword(&p.name) {
            format!("arg{i}")
        } else {
            p.name.clone()
        };
        out.push((name, ty));
    }
    Some(out)
}

/// Names that can't be used as a free-function parameter in Rust. Covers
/// strict keywords + the handful of reserved words that show up in C
/// signatures (`type`, `self`, `match`, …). Not exhaustive of every Rust
/// keyword — only those that would actually appear in TOML param names.
fn is_rust_keyword(s: &str) -> bool {
    matches!(
        s,
        "as" | "async"
            | "await"
            | "box"
            | "break"
            | "const"
            | "continue"
            | "crate"
            | "do"
            | "dyn"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "priv"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "try"
            | "type"
            | "typeof"
            | "union"
            | "unsafe"
            | "unsized"
            | "use"
            | "virtual"
            | "where"
            | "while"
            | "yield"
    )
}

/// Returns `None` if the return type doesn't resolve. Returns `Some(None)` for
/// `void` (so the wrapper omits the `-> R` clause).
fn resolve_return(cat: &Catalog, sig: &Signature) -> Option<Option<String>> {
    let rendered = parse_type_ref(&sig.returns, cat).render().ok()?;
    Some(if rendered == "core::ffi::c_void" {
        None
    } else {
        Some(rendered)
    })
}

/// Map TOML `calling_convention` string to the Rust ABI keyword used inside
/// `extern "X" fn`. Returns `None` for missing or unrecognised values, and
/// for any function with `custom_storage = true` (caller filters earlier).
fn base_calling_convention(f: &Function) -> Option<&'static str> {
    match f.calling_convention.as_deref()? {
        "__stdcall" => Some("stdcall"),
        "__cdecl" => Some("cdecl"),
        "__thiscall" => Some("thiscall"),
        "__fastcall" => Some("fastcall"),
        _ => None,
    }
}

fn class_prefix(name: &str) -> Option<&str> {
    let idx = name.find("__")?;
    if idx == 0 {
        return None;
    }
    let prefix = &name[..idx];
    if prefix
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '_')
    {
        Some(prefix)
    } else {
        None
    }
}

fn member_part(name: &str) -> Option<&str> {
    let idx = name.find("__")?;
    Some(&name[idx + 2..])
}

fn is_valid_rust_ident(s: &str) -> bool {
    let mut chars = s.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first.is_ascii_alphabetic() || first == '_') {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

#[cfg(test)]
mod tests {
    use super::*;
    use openwa_re_data::model::{Function, Param, Signature, Struct};
    use openwa_re_data::toml_io::{Catalog, OwnedEntry};
    use std::path::PathBuf;

    fn fn_with(
        va: u32,
        name: &str,
        cc: Option<&str>,
        custom: bool,
        ret: Option<&str>,
        params: Vec<(&str, &str)>,
    ) -> Function {
        Function {
            va,
            name: name.into(),
            calling_convention: cc.map(str::to_string),
            plate_comment: None,
            no_return: false,
            custom_storage: custom,
            signature: ret.map(|r| Signature {
                returns: r.into(),
                return_storage: None,
            }),
            param: params
                .into_iter()
                .map(|(n, t)| Param {
                    name: n.into(),
                    ty: t.into(),
                    storage: None,
                })
                .collect(),
            local: vec![],
            comment: vec![],
        }
    }

    fn cat_with(fns: Vec<Function>) -> Catalog {
        let mut c = Catalog::default();
        for f in fns {
            c.functions.insert(
                f.va,
                OwnedEntry {
                    value: f,
                    source: PathBuf::from("<test>"),
                },
            );
        }
        c
    }

    fn with_struct(cat: &mut Catalog, name: &str, rust_path: &str) {
        cat.structs.insert(
            name.to_string(),
            OwnedEntry {
                value: Struct {
                    name: name.to_string(),
                    namespace: None,
                    size: 0,
                    plate_comment: None,
                    rust_path: Some(rust_path.to_string()),
                    field: vec![],
                },
                source: PathBuf::from("<test>"),
            },
        );
    }

    #[test]
    fn emits_thiscall_wrapper_with_resolved_pointer() {
        let mut cat = cat_with(vec![fn_with(
            0x00529F30,
            "GameRuntime__StepFrame",
            Some("__thiscall"),
            false,
            Some("int"),
            vec![("this", "GameRuntime *"), ("frame", "int")],
        )]);
        with_struct(
            &mut cat,
            "GameRuntime",
            "openwa_game::engine::runtime::GameRuntime",
        );

        let (out, stats) = generate(&cat);
        assert_eq!(stats.functions_emitted, 1);
        assert!(out.contains("pub mod GameRuntime {"));
        assert!(out.contains("pub unsafe fn StepFrame("));
        assert!(out.contains("this: *mut openwa_game::engine::runtime::GameRuntime"));
        assert!(out.contains("frame: i32"));
        assert!(out.contains("-> i32"));
        assert!(out.contains("unsafe extern \"thiscall\" fn(*mut openwa_game::engine::runtime::GameRuntime, i32) -> i32"));
        assert!(out.contains("crate::generated::addresses::GameRuntime__StepFrame"));
        assert!(out.contains("f(this, frame)"));
    }

    #[test]
    fn omits_return_type_when_void() {
        let mut cat = cat_with(vec![fn_with(
            0x00500000,
            "GameRuntime__ResetFrameState",
            Some("__cdecl"),
            false,
            Some("void"),
            vec![],
        )]);
        with_struct(
            &mut cat,
            "GameRuntime",
            "openwa_game::engine::runtime::GameRuntime",
        );
        let (out, _) = generate(&cat);
        // Signature should NOT have `-> ()` — empty return for clarity.
        assert!(out.contains("pub unsafe fn ResetFrameState()"));
        assert!(!out.contains("-> ()"));
        assert!(out.contains("unsafe extern \"cdecl\" fn()"));
    }

    #[test]
    fn skips_usercall() {
        let cat = cat_with(vec![fn_with(
            0x00529F30,
            "GameRuntime__StepFrame",
            Some("__thiscall"),
            true, // custom_storage
            Some("int"),
            vec![("this", "int")],
        )]);
        let (out, stats) = generate(&cat);
        assert_eq!(stats.skipped_usercall, 1);
        assert_eq!(stats.functions_emitted, 0);
        assert!(!out.contains("StepFrame"));
    }

    #[test]
    fn skips_when_param_type_unresolved() {
        let cat = cat_with(vec![fn_with(
            0x00500000,
            "Foo__bar",
            Some("__stdcall"),
            false,
            Some("int"),
            vec![("x", "BaseEntity *")], // no rust_path → unresolved
        )]);
        let (out, stats) = generate(&cat);
        assert_eq!(stats.skipped_unresolved_type, 1);
        assert_eq!(stats.functions_emitted, 0);
        assert!(!out.contains("Foo__bar"));
    }

    #[test]
    fn skips_when_no_signature_block() {
        let cat = cat_with(vec![fn_with(
            0x00500000,
            "Foo__bar",
            Some("__stdcall"),
            false,
            None, // no signature
            vec![],
        )]);
        let (_, stats) = generate(&cat);
        assert_eq!(stats.skipped_no_return_type, 1);
    }

    #[test]
    fn sanitises_param_name_when_invalid_or_shadowing() {
        let cat = cat_with(vec![fn_with(
            0x00500000,
            "Foo__bar",
            Some("__cdecl"),
            false,
            Some("int"),
            vec![
                ("0bad", "int"), // invalid → arg0
                ("f", "int"),    // shadows local `f` → arg1
            ],
        )]);
        let (out, stats) = generate(&cat);
        assert_eq!(stats.functions_emitted, 1);
        assert!(out.contains("arg0: i32"));
        assert!(out.contains("arg1: i32"));
        assert!(out.contains("f(arg0, arg1)"));
    }

    #[test]
    fn unclassified_function_goes_in_free_module() {
        let cat = cat_with(vec![fn_with(
            0x0053F320,
            "AdvanceGameRng",
            Some("__fastcall"),
            false,
            Some("uint"),
            vec![("state", "uint")],
        )]);
        let (out, stats) = generate(&cat);
        assert_eq!(stats.functions_emitted, 1);
        assert!(out.contains("pub mod free {"));
        assert!(out.contains("pub unsafe fn AdvanceGameRng("));
    }

    #[test]
    fn empty_class_module_is_not_emitted() {
        // Every member is usercall → no wrappers → don't emit `pub mod Foo {}`.
        let cat = cat_with(vec![fn_with(
            0x00500000,
            "Foo__bar",
            Some("__thiscall"),
            true,
            Some("void"),
            vec![("this", "int")],
        )]);
        let (out, _) = generate(&cat);
        assert!(!out.contains("pub mod Foo"));
    }
}
