//! Generate symbolic names for WA.exe's `g_LocalizationKeyTable` entries.
//!
//! Input: `data/string_resources.txt` — one name per line, in order.
//! Output: `$OUT_DIR/string_resource.rs` — `StringRes` newtype, `res::*` constants,
//! and a `NAMES` lookup table. See `src/wa/string_resource.rs` for the wrapping API.

use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

fn main() {
    let input = "data/string_resources.txt";
    println!("cargo:rerun-if-changed={input}");

    let raw = fs::read_to_string(input).expect("read string_resources.txt");

    let names: Vec<&str> = raw
        .lines()
        .map(|l| l.trim())
        .filter(|l| !l.is_empty())
        .collect();

    for (i, name) in names.iter().enumerate() {
        if !name.chars().all(|c| c == '_' || c.is_ascii_alphanumeric()) {
            panic!("line {}: invalid name {:?}", i + 1, name);
        }
    }

    let count = names.len();

    let out_dir: PathBuf = env::var_os("OUT_DIR").expect("OUT_DIR").into();
    let mut out = fs::File::create(out_dir.join("string_resource.rs")).expect("create output");

    writeln!(
        out,
        "// Generated by build.rs from data/string_resources.txt. Do not edit."
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#[repr(transparent)]").unwrap();
    writeln!(out, "#[derive(Copy, Clone, Eq, PartialEq, Hash)]").unwrap();
    writeln!(out, "pub struct StringRes(u32);").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "impl StringRes {{").unwrap();
    writeln!(out, "    pub const COUNT: u32 = {count};").unwrap();
    writeln!(
        out,
        "    #[inline] pub const fn from_offset(id: u32) -> Option<Self> {{"
    )
    .unwrap();
    writeln!(
        out,
        "        if id < Self::COUNT {{ Some(Self(id)) }} else {{ None }}"
    )
    .unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(
        out,
        "    #[inline] pub const fn new_unchecked(id: u32) -> Self {{ Self(id) }}"
    )
    .unwrap();
    writeln!(
        out,
        "    #[inline] pub const fn as_offset(self) -> u32 {{ self.0 }}"
    )
    .unwrap();
    writeln!(
        out,
        "    #[inline] pub fn name(self) -> &'static str {{ NAMES[self.0 as usize] }}"
    )
    .unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "impl core::fmt::Debug for StringRes {{").unwrap();
    writeln!(
        out,
        "    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {{"
    )
    .unwrap();
    writeln!(out, "        write!(f, \"StringRes::{{}}\", self.name())").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "static NAMES: [&str; StringRes::COUNT as usize] = [").unwrap();
    for name in &names {
        writeln!(out, "    \"{name}\",").unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#[allow(non_upper_case_globals)]").unwrap();
    writeln!(out, "pub mod res {{").unwrap();
    writeln!(out, "    use super::StringRes;").unwrap();
    for (i, name) in names.iter().enumerate() {
        writeln!(
            out,
            "    pub const {name}: StringRes = StringRes::new_unchecked({i});"
        )
        .unwrap();
    }
    writeln!(out, "}}").unwrap();
}
