//! Build-time codegen for openwa-game.
//!
//! Two outputs, both written to `$OUT_DIR` and included via `src/`:
//! 1. `string_resource.rs` — `StringRes` newtype + `res::*` constants from
//!    `data/string_resources.txt`. See `src/wa/string_resource.rs`.
//! 2. `generated_addresses.rs` — `pub const NAME: u32` + `inventory::submit!`
//!    entries derived from `re/**/*.toml` via `openwa-re-codegen`. Included
//!    by `src/generated/mod.rs`. See plan
//!    `C:\Users\Paavo\.claude\plans\we-ve-recently-added-the-structured-snowflake.md`.

use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

fn main() {
    generate_string_resources();
    generate_re_artifacts();
}

fn generate_string_resources() {
    let input = "data/string_resources.txt";
    println!("cargo:rerun-if-changed={input}");

    let raw = fs::read_to_string(input).expect("read string_resources.txt");

    let names: Vec<&str> = raw
        .lines()
        .map(|l| l.trim())
        .filter(|l| !l.is_empty())
        .collect();

    for (i, name) in names.iter().enumerate() {
        if !name.chars().all(|c| c == '_' || c.is_ascii_alphanumeric()) {
            panic!("line {}: invalid name {:?}", i + 1, name);
        }
    }

    let count = names.len();

    let out_dir: PathBuf = env::var_os("OUT_DIR").expect("OUT_DIR").into();
    let mut out = fs::File::create(out_dir.join("string_resource.rs")).expect("create output");

    writeln!(
        out,
        "// Generated by build.rs from data/string_resources.txt. Do not edit."
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#[repr(transparent)]").unwrap();
    writeln!(out, "#[derive(Copy, Clone, Eq, PartialEq, Hash)]").unwrap();
    writeln!(out, "pub struct StringRes(u32);").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "impl StringRes {{").unwrap();
    writeln!(out, "    pub const COUNT: u32 = {count};").unwrap();
    writeln!(
        out,
        "    #[inline] pub const fn from_offset(id: u32) -> Option<Self> {{"
    )
    .unwrap();
    writeln!(
        out,
        "        if id < Self::COUNT {{ Some(Self(id)) }} else {{ None }}"
    )
    .unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(
        out,
        "    #[inline] pub const fn new_unchecked(id: u32) -> Self {{ Self(id) }}"
    )
    .unwrap();
    writeln!(
        out,
        "    #[inline] pub const fn as_offset(self) -> u32 {{ self.0 }}"
    )
    .unwrap();
    writeln!(
        out,
        "    #[inline] pub fn name(self) -> &'static str {{ NAMES[self.0 as usize] }}"
    )
    .unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "impl core::fmt::Debug for StringRes {{").unwrap();
    writeln!(
        out,
        "    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {{"
    )
    .unwrap();
    writeln!(out, "        write!(f, \"StringRes::{{}}\", self.name())").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "static NAMES: [&str; StringRes::COUNT as usize] = [").unwrap();
    for name in &names {
        writeln!(out, "    \"{name}\",").unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#[allow(non_upper_case_globals)]").unwrap();
    writeln!(out, "pub mod res {{").unwrap();
    writeln!(out, "    use super::StringRes;").unwrap();
    for (i, name) in names.iter().enumerate() {
        writeln!(
            out,
            "    pub const {name}: StringRes = StringRes::new_unchecked({i});"
        )
        .unwrap();
    }
    writeln!(out, "}}").unwrap();
}

fn generate_re_artifacts() {
    // Workspace root = crates/openwa-game/.. -> crates/.. -> workspace root.
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap());
    let workspace = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("workspace root above crates/openwa-game");
    let re_dir = workspace.join("re");

    // Track every TOML so cargo rebuilds when any of them change. Also emit
    // the directory itself — covers added/removed files on cargo versions
    // that hash dir mtimes.
    println!("cargo:rerun-if-changed={}", re_dir.display());
    for entry in walkdir::WalkDir::new(&re_dir)
        .into_iter()
        .filter_map(|r| r.ok())
    {
        let p = entry.path();
        if p.extension().and_then(|e| e.to_str()) == Some("toml") {
            println!("cargo:rerun-if-changed={}", p.display());
        }
    }

    let cat = openwa_re_codegen::Catalog::load_from(&re_dir).expect("loading re/ catalog");
    let out_dir: PathBuf = env::var_os("OUT_DIR").unwrap().into();

    // generated_addresses.rs — `pub const NAME: u32` + inventory entries.
    let (addr_source, addr_stats) = openwa_re_codegen::emit_addresses::generate(&cat);
    fs::write(out_dir.join("generated_addresses.rs"), addr_source)
        .expect("writing generated_addresses.rs");

    println!(
        "cargo:warning=addresses: emitted {} fns + {} globals; skipped {} fns + {} globals (invalid ident), {} fns + {} globals (dup name)",
        addr_stats.functions_emitted,
        addr_stats.globals_emitted,
        addr_stats.functions_skipped_invalid_ident,
        addr_stats.globals_skipped_invalid_ident,
        addr_stats.functions_skipped_duplicate_name,
        addr_stats.globals_skipped_duplicate_name,
    );

    // generated_wa_calls.rs — typed Path-A wrappers (transmute call-throughs).
    let (calls_source, calls_stats) = openwa_re_codegen::emit_wa_calls::generate(&cat);
    fs::write(out_dir.join("generated_wa_calls.rs"), calls_source)
        .expect("writing generated_wa_calls.rs");

    println!(
        "cargo:warning=wa_calls: emitted {} fns; skipped {} (no conv), {} (unknown conv), {} (usercall), {} (no ret type), {} (unresolved type), {} (invalid ident), {} (dup member)",
        calls_stats.functions_emitted,
        calls_stats.skipped_no_convention,
        calls_stats.skipped_unknown_convention,
        calls_stats.skipped_usercall,
        calls_stats.skipped_no_return_type,
        calls_stats.skipped_unresolved_type,
        calls_stats.skipped_invalid_member_ident,
        calls_stats.skipped_duplicate_member,
    );
}
