use super::base::BaseEntity;
use crate::FieldRegistry;
use openwa_core::fixed::Fixed;

// `WORLD_ENTITY_VTABLE` and `SOUND_EMITTER_VTABLE` are generated by the
// `#[vtable(va = ...)]` attributes on `WorldEntityVtable` / `SoundEmitterVtable`.
crate::define_addresses! {
    class "WorldEntity" {
        ctor/Stdcall CGAMETASK_CONSTRUCTOR = 0x004FED50;
        vmethod CGAMETASK_VT0 = 0x004FF1C0;
        vmethod CGAMETASK_VT1_FREE = 0x004FEF10;
        vmethod CGAMETASK_VT2_HANDLE_MESSAGE = 0x004FF280;
        /// `WorldEntity__TryMovePosition` (free function). 50+ direct
        /// callers across every WorldEntity subclass. Usercall:
        /// `ESI=this, EDI=y, [ESP+4]=x`, RET 0x4. Ported as
        /// [`WorldEntity::try_move_position_raw`].
        fn TRY_MOVE_POSITION = 0x004FE070;
        /// Movement validity / collision-response check used by
        /// `try_move_position`. Stdcall, 6 args, RET 0x18. Returns nonzero
        /// to reject the move (caller leaves position unchanged).
        fn/Stdcall CHECK_MOVE_COLLISION = 0x004FB9D0;
    }
}

pub const CGAMETASK_SOUND_EMITTER_VT: u32 = SOUND_EMITTER_VTABLE;
pub const CGAMETASK_VTABLE: u32 = WORLD_ENTITY_VTABLE;

/// Game task - extends BaseEntity with physics and gameplay data.
///
/// PARTIAL: Most fields between 0x30-0x83 and 0x98-0xE7 are unknown.
/// Only position and velocity fields have been verified.
///
/// Source: wkJellyWorm WorldEntity.h
///
/// Additional vtable (12 methods at offsets 0x1C-0x48 in vtable)
#[derive(FieldRegistry)]
#[repr(C)]
pub struct WorldEntity<V: super::base::Vtable = *const core::ffi::c_void> {
    /// 0x00-0x2F: Base BaseEntity fields
    pub base: BaseEntity<V>,
    /// 0x30-0x83: Subclass-specific data (84 bytes). Each WorldEntity derivative
    /// uses this region differently:
    /// - WormEntity: weapon fire state (+0x30 type, +0x34/+0x38 subtypes, +0x3C flag)
    /// - FilterEntity: boolean message subscription table (+0x30..+0x93)
    /// - MissileEntity: spawn/physics parameters
    /// - TeamEntity: secondary vtable pointer (+0x30)
    /// - CloudEntity: parallax scroll depth (+0x30)
    /// Access via subclass accessor methods, not directly.
    pub subclass_data: [u8; 0x54],
    /// 0x84: X position in fixed-point
    pub pos_x: Fixed,
    /// 0x88: Y position in fixed-point
    pub pos_y: Fixed,
    /// 0x8C: Rotation angle (fixed-point 16.16).
    pub angle: Fixed,
    /// 0x90: X velocity in fixed-point
    pub speed_x: Fixed,
    /// 0x94: Y velocity in fixed-point
    pub speed_y: Fixed,
    /// 0x98-0xCB: Unknown gameplay fields.
    pub _unknown_98: [u8; 0x34],
    /// 0xCC: Per-entity scale (Fixed16.16) applied to received explosion
    /// knockback impulses. Initialised to `1.0` (`0x10000`) by
    /// `WorldEntity::Constructor` (0x004FED50, dword index `0x33`); read by
    /// `WorldEntity::ComputeExplosionDamage` (0x004FF390) as the per-axis
    /// recoil multiplier. Writers are not yet identified, so subclasses may
    /// use it for an unrelated purpose.
    pub _field_cc: Fixed,
    /// 0xD0-0xD3: Unknown gameplay fields.
    pub _unknown_d0: [u8; 0x4],
    /// 0xD4: Per-entity damage accumulator. `WorldEntity::HandleMessage`
    /// (msg=0x1c, Explosion) adds the falloff-adjusted damage from each
    /// blast into this slot.
    pub damage_accum: i32,
    /// 0xD8-0xDF: Unknown gameplay fields
    pub _unknown_d8: [u8; 0x8],
    /// 0xE0: Owned sound-emitter handle, or 0 when no sound is held.
    /// `WorldEntity::HandleMessage` (msg=0x02, FrameFinish) polls the sound
    /// subsystem each frame and clears this slot once the sound has
    /// finished playing.
    pub sound_handle: u32,
    /// 0xE4: Unknown
    pub _unknown_e4: u32,
    /// 0xE8: Embedded sound emitter sub-object (MSVC multiple inheritance).
    pub sound_emitter: SoundEmitter,
}

const _: () = assert!(core::mem::size_of::<WorldEntity>() == 0xFC);

/// 20-slot vtable shared by every `WorldEntity` derivative — subclass
/// vtables (e.g. `WormEntityVtable`) layer their own overrides on top of
/// the same shape. Only slots dispatched from Rust are spelled out.
#[openwa_game::vtable(size = 20, va = 0x006641F8, class = "WorldEntity")]
pub struct WorldEntityVtable {
    /// `AddImpulse` (0x00500090). Divides each axis by mass at `+0x4c`,
    /// accumulates into `speed_x`/`speed_y`, adds `dz` raw to `+0x98`.
    /// Bails (returns 0) when `+0x48` is non-zero — the slot doubles as
    /// HP on receiver subclasses (mines, drums, crosses, score bubbles).
    #[slot(17)]
    pub add_impulse: fn(this: *mut WorldEntity, impulse_x: Fixed, impulse_y: Fixed, dz: i32) -> u32,
}

impl WorldEntity {
    /// Dispatch slot 17 through the typed vtable shape. The cast is
    /// byte-identical for every subclass since they all extend the same
    /// 20-slot layout, so calling from `WormEntity`/`MineEntity`/… picks
    /// up that subclass's override.
    #[inline]
    pub unsafe fn add_impulse_raw(
        this: *mut WorldEntity,
        impulse_x: Fixed,
        impulse_y: Fixed,
        dz: i32,
    ) -> u32 {
        unsafe {
            let vt = *(this as *const *const WorldEntityVtable);
            ((*vt).add_impulse)(this, impulse_x, impulse_y, dz)
        }
    }

    /// Pure Rust port of `WorldEntity__TryMovePosition` (0x004FE070).
    ///
    /// Asks the collision/move-validity helper at
    /// [`CHECK_MOVE_COLLISION`] (0x004FB9D0) whether the entity may move to
    /// `(x, y)`. On accept (helper returns 0), commits the new position by
    /// writing `pos_x`/`pos_y` and clamping the +0xAC counter to 0 if it was
    /// positive, then returns 1. On reject, leaves the entity unchanged and
    /// returns 0.
    ///
    /// The helper is `__stdcall` with 6 args (RET 0x18); both `+0x34` (the
    /// first dword of `subclass_data`) and `+0xDC` (inside `_unknown_d8`) are
    /// passed verbatim — both are subclass-polymorphic. WA itself called this
    /// with `__usercall(ESI=this, EDI=y, [ESP+4]=x)`; the Rust port takes
    /// plain args and lets the stdcall ABI handle register loading.
    ///
    /// Used by every `WorldEntity` subclass — constructors call it to do the
    /// initial placement check, and movement code re-uses it to commit each
    /// step.
    #[inline]
    pub unsafe fn try_move_position_raw(this: *mut WorldEntity, x: i32, y: i32) -> u32 {
        unsafe {
            use crate::rebase::rb;

            let world = (*(this as *const BaseEntity)).world;
            let game_state_stream = (*world).game_state_stream;

            let base = this as *const u8;
            let p_dc = *(base.add(0xDC) as *const u32);
            let p_34 = *(base.add(0x34) as *const u32);

            type Helper =
                unsafe extern "stdcall" fn(*mut u8, *mut WorldEntity, i32, i32, u32, u32) -> u32;
            let helper: Helper = core::mem::transmute(rb(CHECK_MOVE_COLLISION));
            if helper(game_state_stream, this, x, y, p_dc, p_34) != 0 {
                return 0;
            }

            (*this).pos_x = Fixed(x);
            (*this).pos_y = Fixed(y);

            let p_ac = base.add(0xAC) as *mut i32;
            if *p_ac > 0 {
                *p_ac = 0;
            }
            1
        }
    }

    /// Pure Rust port of `FUN_004FB580` — "is this entity in motion?".
    ///
    /// Returns `true` iff any of `speed_x` (+0x90), `speed_y` (+0x94), or the
    /// three unknown gameplay scalars at +0xB0/+0xB4/+0xB8 are non-zero.
    /// The +0xBx triplet lives in [`Self::_unknown_98`]; semantics are not yet
    /// nailed down (likely the spin/torque components paired with `pos_z`/
    /// `speed_z`), but together with `speed_x/_y` they form the canonical
    /// "this body is still moving" predicate WA uses across `WormEntity`,
    /// `MineEntity`, `MissileEntity`, `OilDrumEntity`, etc. (16 callers).
    #[inline]
    pub unsafe fn is_moving_raw(this: *const WorldEntity) -> bool {
        unsafe {
            let base = this as *const u8;
            *(base.add(0x90) as *const i32) != 0
                || *(base.add(0x94) as *const i32) != 0
                || *(base.add(0xB0) as *const i32) != 0
                || *(base.add(0xB4) as *const i32) != 0
                || *(base.add(0xB8) as *const i32) != 0
        }
    }
}

/// Sound emitter sub-object embedded in WorldEntity via MSVC multiple inheritance.
///
/// Provides spatial audio support. The `this` pointer for its vtable methods
/// points to the start of this sub-object (WorldEntity+0xE8), not the WorldEntity.
#[repr(C)]
pub struct SoundEmitter {
    /// +0x00: Vtable pointer
    pub vtable: *const SoundEmitterVtable,
    /// +0x04: Unknown field
    pub _unknown_04: u32,
    /// +0x08: Reference count — incremented when an ActiveSoundEntry holds this emitter,
    /// decremented when the entry is released.
    pub local_ref_count: i32,
    /// +0x0C: Number of active local sounds
    pub local_sound_count: i32,
    /// +0x10: Back-pointer to containing WorldEntity
    pub owner: *mut WorldEntity,
}

const _: () = assert!(core::mem::size_of::<SoundEmitter>() == 0x14);

/// Vtable for the SoundEmitter sub-object (0x669CF8, 12 slots).
///
/// Slots [0]-[4] are the sound emitter's own interface.
/// Slots [5]-[11] are inherited BaseEntity base methods.
#[openwa_game::vtable(size = 12, va = 0x00669CF8, class = "SoundEmitter")]
pub struct SoundEmitterVtable {
    /// GetPosition(this, out_x, out_y) — reads pos_x/pos_y via owner
    #[slot(0)]
    pub get_position: fn(this: *const SoundEmitter, out_x: *mut u32, out_y: *mut u32),
    /// GetPosition2 — reads WorldEntity+0x38/0x3C
    #[slot(1)]
    pub get_position2: fn(this: *const SoundEmitter, out_x: *mut u32, out_y: *mut u32),
    /// Destructor
    #[slot(3)]
    pub destructor: fn(this: *mut SoundEmitter, flags: u32) -> *mut SoundEmitter,
    /// HandleMessage — sound queue manager
    #[slot(4)]
    pub handle_message:
        fn(this: *mut SoundEmitter, sender: u32, msg_type: u32, size: u32, data: u32),
}
