[[function]]
va = 0x0054F4C0
name = "FireEntity__Constructor"

[[function]]
va = 0x0054F680
name = "FireEntity__Free"

[[function]]
va = 0x0054F770
name = "FireEntity__Init"

[[function]]
va = 0x005501A0
name = "FireEntity__HandleMessage"
calling_convention = "__thiscall"

  [function.signature]
  returns = "void"

  [[function.param]]
  name = "this"
  type = "void *"

  [[function.param]]
  name = "sender"
  type = "void *"

  [[function.param]]
  name = "msg_type"
  type = "EntityMessage"

  [[function.param]]
  name = "size"
  type = "uint"

  [[function.param]]
  name = "data"
  type = "void *"

[[function]]
va = 0x005509E0
name = "FireEntity__ProcessFrame"

[[global]]
va = 0x00669DD8
name = "FireEntity__vtable"

[[function]]
va = 0x0054F6D0
name = "FireEntity__ctor1_FireEntity"

[[function]]
va = 0x0054F7D0
name = "FireEntity__insert_into_firelist"

[[function]]
va = 0x0054F940
name = "FireEntity__create_fire"

[[function]]
va = 0x0054FAD0
name = "FireEntity__check_for_impact"

[[function]]
va = 0x0054FD40
name = "FireEntity__emit_smoke"

[[function]]
va = 0x0054FE20
name = "FireEntity__update_falling"

[[function]]
va = 0x00550100
name = "FireEntity__update_burning"

[[function]]
va = 0x00550140
name = "FireEntity__perform_burning"

[[function]]
va = 0x005506F0
name = "FireEntity__blast"
