[[function]]
va = 0x00554750
name = "GasEntity__Constructor"
calling_convention = "__stdcall"
custom_storage = true

  [function.signature]
  returns = "void"

  [[function.param]]
  name = "this"
  type = "void *"
  storage = "ESI"

  [[function.param]]
  name = "parent"
  type = "void *"
  storage = "EAX"

  [[function.param]]
  name = "spawn_x"
  type = "Fixed"
  storage = "stack:0x4"

  [[function.param]]
  name = "spawn_y"
  type = "Fixed"
  storage = "stack:0x8"

  [[function.param]]
  name = "sprite"
  type = "uint"
  storage = "stack:0xC"

  [[function.param]]
  name = "owner"
  type = "uint"
  storage = "stack:0x10"

[[function]]
va = 0x00554810
name = "GasEntity__ctor1_GasEntity"

[[function]]
va = 0x005548E0
name = "GasEntity__save"

[[function]]
va = 0x00554980
name = "GasEntity__check_for_target"

[[function]]
va = 0x00554A70
name = "GasEntity__message"
