[[function]]
va = 0x004AA060
name = "WorldEntity__vt19"

[[function]]
va = 0x004FB580
name = "WorldEntity__IsMoving"

[[function]]
va = 0x004FB9D0
name = "WorldEntity__CheckMoveCollision"

[[function]]
va = 0x004FE060
name = "WorldEntity__SetTerminateFlag_Maybe"

[[function]]
va = 0x004FE070
name = "WorldEntity__TryMovePosition"
calling_convention = "__stdcall"
custom_storage = true

  [function.signature]
  returns = "uint"

  [[function.param]]
  name = "this"
  type = "WorldEntity *"
  storage = "ESI"

  [[function.param]]
  name = "y"
  type = "Fixed"
  storage = "EDI"

  [[function.param]]
  name = "x"
  type = "Fixed"
  storage = "stack:0x4"

[[function]]
va = 0x004FED50
name = "WorldEntity__Constructor"

[[function]]
va = 0x004FEF10
name = "WorldEntity__vt1_Free"

[[function]]
va = 0x004FF1C0
name = "WorldEntity__vt0_override"

[[function]]
va = 0x004FF280
name = "WorldEntity__vt2_HandleMessage"
calling_convention = "__thiscall"
custom_storage = true

  [function.signature]
  returns = "void"

  [[function.param]]
  name = "this"
  type = "WorldEntity *"
  storage = "ECX"

  [[function.param]]
  name = "sender"
  type = "BaseEntity *"
  storage = "stack:0x4"

  [[function.param]]
  name = "msg_type"
  type = "EntityMessage"
  storage = "stack:0x8"

  [[function.param]]
  name = "size"
  type = "uint"
  storage = "stack:0xC"

  [[function.param]]
  name = "data"
  type = "void *"
  storage = "stack:0x10"

[[function]]
va = 0x004FF390
name = "WorldEntity__ComputeExplosionDamage"
calling_convention = "__stdcall"
custom_storage = true

  [function.signature]
  returns = "int"

  [[function.param]]
  name = "this"
  type = "WorldEntity *"
  storage = "EDI"

  [[function.param]]
  name = "strength"
  type = "uint"
  storage = "stack:0x4"

  [[function.param]]
  name = "damage"
  type = "uint"
  storage = "stack:0x8"

  [[function.param]]
  name = "pos_x"
  type = "Fixed"
  storage = "stack:0xC"

  [[function.param]]
  name = "pos_y"
  type = "Fixed"
  storage = "stack:0x10"

[[function]]
va = 0x004FF720
name = "WorldEntity__vt7"

[[function]]
va = 0x004FFED0
name = "WorldEntity__vt8"

[[function]]
va = 0x00501E20
name = "WorldEntity__vt7"

[[function]]
va = 0x005262D0
name = "WorldEntity__InitAllianceData"
calling_convention = "__cdecl"
custom_storage = true

  [function.signature]
  returns = "void"

  [[function.param]]
  name = "runtime"
  type = "GameRuntime *"
  storage = "EAX"

[[function]]
va = 0x00528510
name = "WorldEntity__InitTeamScoring"
calling_convention = "__fastcall"

  [function.signature]
  returns = "void"

  [[function.param]]
  name = "runtime"
  type = "GameRuntime *"

[[function]]
va = 0x00528690
name = "WorldEntity__InitTurnState"
calling_convention = "__cdecl"
custom_storage = true

  [function.signature]
  returns = "void"

  [[function.param]]
  name = "runtime"
  type = "GameRuntime *"
  storage = "EAX"

[[function]]
va = 0x00545780
name = "WorldEntity__vt18"

[[function]]
va = 0x00546680
name = "WorldEntity__SecondaryVT__GetPosition_Maybe"

[[function]]
va = 0x005466A0
name = "WorldEntity__SecondaryVT__Slot1"

[[function]]
va = 0x00546CD0
name = "WorldEntity__IsSoundHandleExpired"
calling_convention = "__cdecl"
custom_storage = true

  [function.signature]
  returns = "uint"

  [[function.param]]
  name = "this"
  type = "WorldEntity *"
  storage = "ECX"

  [[function.param]]
  name = "handle"
  type = "uint"
  storage = "EAX"

[[function]]
va = 0x00546D20
name = "WorldEntity__ReleaseSoundHandle"

[[function]]
va = 0x0054B7A0
name = "WorldEntity__SecondaryVtable_ProcessFrame_Maybe"

[[function]]
va = 0x00592A50
name = "WorldEntity__vt16"

[[global]]
va = 0x006641F8
name = "WorldEntity__vtable"

[[global]]
va = 0x00669CF8
name = "WorldEntity__vtable2"

[[struct]]
name = "WorldEntity"
namespace = "/OpenWA"
size = 0xFC
rust_path = "openwa_game::entity::game_entity::WorldEntity"
