use core::ffi::c_void;
use core::sync::atomic::{AtomicU32, Ordering};

use super::base::BaseEntity;
use crate::FieldRegistry;
use crate::engine::team_arena::TeamArena;
use crate::game::class_type::ClassType;
use crate::rebase::rb;
use openwa_core::fixed::Fixed;

// `WORLD_ENTITY_VTABLE` and `SOUND_EMITTER_VTABLE` are generated by the
// `#[vtable(va = ...)]` attributes on `WorldEntityVtable` / `SoundEmitterVtable`.
crate::define_addresses! {
    class "WorldEntity" {
        ctor/Stdcall CGAMETASK_CONSTRUCTOR = 0x004FED50;
        vmethod CGAMETASK_VT0 = 0x004FF1C0;
        vmethod CGAMETASK_VT1_FREE = 0x004FEF10;
        vmethod CGAMETASK_VT2_HANDLE_MESSAGE = 0x004FF280;
        /// `WorldEntity__TryMovePosition` (free function). 50+ direct
        /// callers across every WorldEntity subclass. Usercall:
        /// `ESI=this, EDI=y, [ESP+4]=x`, RET 0x4. Ported as
        /// [`WorldEntity::try_move_position_raw`].
        fn TRY_MOVE_POSITION = 0x004FE070;
        /// `WorldEntity__CheckMoveCollision` — movement validity /
        /// collision-response check used by `try_move_position`. Pure-Rust
        /// port at [`WorldEntity::check_move_collision_raw`]; the WA
        /// function still has 40+ in-game callers we don't replace.
        fn/Stdcall CHECK_MOVE_COLLISION = 0x004FB9D0;
    }
    /// `CollisionManager::update_intersections` (0x004FBC30) — refreshes
    /// the per-entity intersection cache stored on `game_state_stream`.
    /// Usercall: `EDI = gss, ESI = this`, no stack args, plain RET. The
    /// callee preserves ESI/EDI per ABI; bridged with a naked trampoline.
    fn/Usercall COLLISION_UPDATE_INTERSECTIONS = 0x004FBC30;
}

pub const CGAMETASK_SOUND_EMITTER_VT: u32 = SOUND_EMITTER_VTABLE;
pub const CGAMETASK_VTABLE: u32 = WORLD_ENTITY_VTABLE;

/// Marker trait for the per-subclass storage block at WorldEntity+0x38..+0x84.
///
/// Implementors must be `#[repr(C)]` and exactly 0x4C bytes — each derivative
/// declares its own struct (e.g. [`MissileSubclassData`](crate::entity::MissileSubclassData))
/// and plugs it into [`WorldEntity<V, S>`]. The default impl on `[u8; 0x4C]`
/// keeps untyped access working for subclasses that haven't been ported yet.
///
/// # Safety
/// Implementors must be 0x4C bytes; verify with a const assertion at the impl
/// site (the trait can't enforce this directly without `generic_const_exprs`).
pub unsafe trait SubclassData: 'static {}

unsafe impl SubclassData for [u8; 0x4C] {}

/// Game entity - extends BaseEntity with physics and gameplay data.
///
/// PARTIAL: Most fields between 0x38-0x83 and 0x98-0xE7 are unknown.
/// Only position and velocity fields have been verified.
///
/// Source: wkJellyWorm WorldEntity.h
///
/// Additional vtable (12 methods at offsets 0x1C-0x48 in vtable)
#[derive(FieldRegistry)]
#[repr(C)]
pub struct WorldEntity<
    V: super::base::Vtable = *const core::ffi::c_void,
    S: SubclassData = [u8; 0x4C],
> {
    /// 0x00-0x2F: Base BaseEntity fields
    pub base: BaseEntity<V>,
    /// 0x30: "Contact face / trigger class" byte. Read by
    /// [`MissileEntity::OnContact`](crate::entity::missile) as the face index of
    /// the contacted entity, and by [`MineEntity::ScanForTrigger`](crate::entity::mine)
    /// as a low-5-bits trigger-class index gating mine proximity hits. Most
    /// WorldEntity subclasses leave this zero-initialised (they're
    /// effectively "face 0 / trigger class 0"); multi-face terrain entities
    /// encode their actual face index here. Subclasses also see scratch
    /// writes from the collision dispatcher just before slot 8 (`OnContact`)
    /// is invoked on a contacting entity, but no subclass durably stores
    /// anything else of its own at this offset.
    pub contact_face: u32,
    /// 0x34: Per-entity collision bucket bitmask. Read by
    /// [`WorldEntity::check_move_collision_raw`] (bit `N` set ⇒ scan
    /// bucket `N` for collisions). Subclasses may rewrite this mid-life
    /// to switch their collision target set — e.g. `MineEntity` writes
    /// `1 << 22` the first frame it enters water, plausibly switching
    /// from a worm/dry-terrain bucket set to a water-specific one so it
    /// continues to sink and interact with water-side collidables.
    pub bucket_mask: u32,
    /// 0x38-0x83: Per-subclass storage (0x4C bytes). Default `[u8; 0x4C]`
    /// for subclasses that haven't been ported to typed views yet; ported
    /// subclasses pass their own `#[repr(C)]` struct (e.g.
    /// [`MissileSubclassData`](crate::entity::MissileSubclassData)).
    pub subclass_data: S,
    /// 0x84: X position in fixed-point
    pub pos_x: Fixed,
    /// 0x88: Y position in fixed-point
    pub pos_y: Fixed,
    /// 0x8C: Rotation angle (fixed-point 16.16).
    pub angle: Fixed,
    /// 0x90: X velocity in fixed-point
    pub speed_x: Fixed,
    /// 0x94: Y velocity in fixed-point
    pub speed_y: Fixed,
    /// 0x98: Slot mutated by [`WorldEntityVtable::add_impulse`] (slot 17),
    /// which adds the `dz` argument raw to this offset alongside dividing
    /// the planar impulse into `speed_x`/`speed_y`. Interpreted as a Fixed
    /// accumulator by [`MineEntity::Render`] (calc_sprite multiplies it by
    /// [`GameWorld::render_interp_a`] and adds [`Self::angle`] to derive the
    /// render-time angle). Subclass semantics may vary; canonical name TBD.
    pub _field_98: Fixed,
    /// 0x9C-0xA3: Unknown gameplay fields.
    pub _unknown_9c: [u8; 8],
    /// 0xA4: Damage-halving + state-pick suppressor read by WormEntity's
    /// damage paths (cases 0x1C/0x76 and 0x4B in `HandleMessage`). When
    /// nonzero the applied damage is halved (`new = damage / 2 + 1`) and
    /// the velocity-based Hurt/HurtAlt state pick is skipped. Writers and
    /// canonical name not yet identified.
    pub _field_a4: u32,
    /// 0xA8-0xAB: Unknown gameplay fields.
    pub _unknown_a8: [u8; 4],
    /// 0xAC: Counter-like field. `try_move_position` clamps it to 0
    /// whenever a position commit succeeds and the slot was positive, so
    /// it accumulates while moves stall and resets on a successful step.
    /// Canonical name from WA's C++ source not yet identified.
    pub _field_ac: i32,
    /// 0xB0: Read by `is_moving_raw` (WorldEntity__IsMoving): any non-zero
    /// contributes to the "this body is still in motion" predicate.
    /// `OilDrumEntity::on_fire` reads the same slot as a non-zero flag —
    /// both readers see the same field; the canonical purpose (likely a
    /// state/timer such as "burning frames remaining" or a torque
    /// component) is not yet identified.
    pub _field_b0: i32,
    /// 0xB4: Contributes to `is_moving_raw` alongside `_field_b0` and
    /// `_field_b8`. Purpose not yet identified.
    pub _field_b4: i32,
    /// 0xB8: Contributes to `is_moving_raw` alongside `_field_b0` and
    /// `_field_b4`. Purpose not yet identified.
    pub _field_b8: i32,
    /// 0xBC: Subclass-overloaded slot. For [`WormEntity`](crate::entity::worm::WormEntity)
    /// it gates the `Jump` (msg 0x24) input-restriction path: when the
    /// per-worm input-lock flag at +0x12A is non-zero, the gate fires only
    /// while this slot is *also* zero. WormEntity also reuses this slot as
    /// the "attached-rope active" gate read by
    /// [`render::worm::draw_attached_rope`](crate::render::worm::draw_attached_rope)
    /// (set to 1 by `InitWormAttachedRope` 0x005008D0). Writers / canonical name TBD.
    pub _field_bc: u32,
    /// 0xC0-0xCB: Unknown gameplay fields.
    pub _unknown_c0: [u8; 0xC],
    /// 0xCC: Per-entity scale (Fixed16.16) applied to received explosion
    /// knockback impulses. Initialised to `1.0` (`0x10000`) by
    /// `WorldEntity::Constructor` (0x004FED50, dword index `0x33`); read by
    /// `WorldEntity::ComputeExplosionDamage` (0x004FF390) as the per-axis
    /// recoil multiplier. Writers are not yet identified, so subclasses may
    /// use it for an unrelated purpose.
    pub _field_cc: Fixed,
    /// 0xD0-0xD3: Unknown gameplay fields.
    pub _unknown_d0: [u8; 0x4],
    /// 0xD4: Per-entity damage accumulator. `WorldEntity::HandleMessage`
    /// (msg=0x1c, Explosion) adds the falloff-adjusted damage from each
    /// blast into this slot.
    pub damage_accum: i32,
    /// 0xD8-0xDB: Unknown gameplay fields.
    pub _unknown_d8: [u8; 0x4],
    /// 0xDC: Pointer to a per-entity collision-shape helper. Read by
    /// [`WorldEntity::check_move_collision_raw`] (and WA's
    /// `CollisionManager::find_intersections`) and dispatched through its
    /// vtable: slot 4 is `intersects(self_x, self_y, other.collision_helper,
    /// other_x, other_y) -> u32`. Stored as a raw pointer because WA writes
    /// it from C++ code we haven't typed yet.
    pub collision_helper: *mut c_void,
    /// 0xE0: Owned sound-emitter handle, or 0 when no sound is held.
    /// `WorldEntity::HandleMessage` (msg=0x02, FrameFinish) polls the sound
    /// subsystem each frame and clears this slot once the sound has
    /// finished playing.
    pub sound_handle: u32,
    /// 0xE4: Unknown
    pub _unknown_e4: u32,
    /// 0xE8: Embedded sound emitter sub-object (MSVC multiple inheritance).
    pub sound_emitter: SoundEmitter,
}

const _: () = assert!(core::mem::size_of::<WorldEntity>() == 0xFC);

/// 20-slot vtable shared by every `WorldEntity` derivative — subclass
/// vtables (e.g. `WormEntityVtable`) layer their own overrides on top of
/// the same shape. Only slots dispatched from Rust are spelled out.
#[openwa_game::vtable(size = 20, va = 0x006641F8, class = "WorldEntity")]
pub struct WorldEntityVtable {
    /// `AddImpulse` (0x00500090). Divides each axis by mass at `+0x4c`,
    /// accumulates into `speed_x`/`speed_y`, adds `dz` raw to `+0x98`.
    /// Bails (returns 0) when `+0x48` is non-zero — the slot doubles as
    /// HP on receiver subclasses (mines, drums, crosses, score bubbles).
    #[slot(17)]
    pub add_impulse: fn(this: *mut WorldEntity, impulse_x: Fixed, impulse_y: Fixed, dz: i32) -> u32,
}

impl<V: super::base::Vtable, S: SubclassData> WorldEntity<V, S> {
    /// Bridge to `WorldEntity::Constructor` (0x004FED50) —
    /// `__stdcall(this, parent, class_type, flag)`, RET 0x10. Subclass
    /// constructors call this once after the caller's heap zero-fill
    /// (e.g. `MineEntity::Constructor` calls
    /// `WorldEntity::construct_raw(&raw mut (*this).base, parent, 10, 2)`).
    /// The WA initializer chains into `BaseEntity::Constructor`, installs
    /// the WorldEntity vtables (the subclass overwrites slot 0 immediately
    /// after), and primes a number of slots in the subclass-data range
    /// with non-zero defaults — most notably entity +0x74 with
    /// `game_info[+0xd780]`. Subclass ctors must therefore explicitly clear
    /// any subclass-data slot they want zeroed.
    ///
    /// Generic over `V` / `S` so subclass-typed pointers can be passed
    /// without an explicit cast; on i686 every `*mut T` is 4 bytes so the
    /// transmute through the default `*mut WorldEntity` is zero-cost.
    #[inline]
    pub unsafe fn construct_raw(
        this: *mut Self,
        parent: *mut BaseEntity,
        class_type: u32,
        flag: u32,
    ) {
        type Fn = unsafe extern "stdcall" fn(*mut WorldEntity, *mut BaseEntity, u32, u32);
        unsafe {
            let f: Fn =
                core::mem::transmute(WORLD_ENTITY_CTOR_ADDR.load(Ordering::Relaxed) as usize);
            f(this as *mut WorldEntity, parent, class_type, flag);
        }
    }
}

impl WorldEntity {
    /// Dispatch slot 17 through the typed vtable shape. The cast is
    /// byte-identical for every subclass since they all extend the same
    /// 20-slot layout, so calling from `WormEntity`/`MineEntity`/… picks
    /// up that subclass's override.
    #[inline]
    pub unsafe fn add_impulse_raw(
        this: *mut WorldEntity,
        impulse_x: Fixed,
        impulse_y: Fixed,
        dz: i32,
    ) -> u32 {
        unsafe {
            let vt = *(this as *const *const WorldEntityVtable);
            ((*vt).add_impulse)(this, impulse_x, impulse_y, dz)
        }
    }

    /// Pure Rust port of `WorldEntity__TryMovePosition` (0x004FE070).
    ///
    /// Asks [`check_move_collision_raw`](Self::check_move_collision_raw)
    /// whether the entity may move to `(x, y)`. On accept (no collision),
    /// commits the new position by writing `pos_x`/`pos_y` and clamping
    /// `_field_ac` to 0 if it was positive, then returns 1. On reject,
    /// leaves the entity unchanged and returns 0.
    ///
    /// WA itself called this with `__usercall(ESI=this, EDI=y, [ESP+4]=x)`;
    /// the Rust port takes plain args and lets the stdcall ABI handle
    /// register loading.
    ///
    /// Used by every `WorldEntity` subclass — constructors call it to do the
    /// initial placement check, and movement code re-uses it to commit each
    /// step.
    #[inline]
    pub unsafe fn try_move_position_raw(this: *mut WorldEntity, x: Fixed, y: Fixed) -> u32 {
        unsafe {
            if !Self::check_move_collision_raw(this, x, y).is_null() {
                return 0;
            }

            (*this).pos_x = x;
            (*this).pos_y = y;

            if (*this)._field_ac > 0 {
                (*this)._field_ac = 0;
            }
            1
        }
    }

    /// Pure Rust port of `WorldEntity__CheckMoveCollision` (0x004FB9D0).
    ///
    /// Returns the colliding entity if `this` cannot move to `(x, y)`, else
    /// null. WA's signature is `__stdcall(gss, this, x, y, helper, mask)`,
    /// RET 0x18, but every known caller passes `helper = this.collision_helper`
    /// and `mask = this.bucket_mask`, so the Rust port reads both directly
    /// from `this`.
    ///
    /// Algorithm:
    ///   1. Read the per-team friendly/enemy fire thresholds from
    ///      `GameInfo`. If either is non-zero, look up the caller's own
    ///      `weapon_alliance` via vtable slot 18 (`GetTeamIndex`) so we can
    ///      gate same- vs cross-alliance contact below.
    ///   2. Refresh the cached intersection set on `game_state_stream` via
    ///      [`COLLISION_UPDATE_INTERSECTIONS`] — that pass marks already-
    ///      overlapping entities with `+0xD8 = 1` so they are skipped here
    ///      (otherwise the caller would always be "stuck inside" itself).
    ///   3. For every bucket selected by `mask`, scan the bucket's entity
    ///      list, drop entries that are self / inactive (`+0x3C == 0`) /
    ///      already-overlapping (`+0xD8 != 0`), apply the alliance gate,
    ///      then run an optional sudden-death water-edge gate before
    ///      finally calling the shape-helper's `intersects` function. Any
    ///      hit returns the offending entity immediately.
    pub unsafe fn check_move_collision_raw(
        this: *mut WorldEntity,
        x: Fixed,
        y: Fixed,
    ) -> *mut WorldEntity {
        unsafe {
            let world = (*(this as *const BaseEntity)).world;
            let game_info = (*world).game_info;
            let gss = (*world).game_state_stream;

            let helper = (*this).collision_helper;
            let bucket_mask = (*this).bucket_mask;

            // -- Alliance-gate setup (mirrors WA: only computed if either
            // threshold is non-zero, since the gate would otherwise never
            // fire).
            let friendly_threshold = (*game_info).friendly_fire_threshold;
            let enemy_threshold = (*game_info).enemy_fire_threshold;
            let mut my_alliance: i32 = -1;
            let mut my_class_is_control = false;
            if friendly_threshold != 0 || enemy_threshold != 0 {
                let team_idx = vt_get_team_index(this);
                if team_idx != 0 {
                    let arena: *const TeamArena = &raw const (*world).team_arena;
                    my_alliance =
                        (*TeamArena::team_header(arena, team_idx as usize)).weapon_alliance;
                }
                my_class_is_control = is_control_class((*(this as *const BaseEntity)).class_type);
            }

            if bucket_mask == 0 {
                return core::ptr::null_mut();
            }

            bridge_update_intersections(gss, this);

            // game_info+0xD972: sudden-death "water edge" gate byte.
            // Currently lives inside _unknown_d96f padding in `GameInfo`.
            let sd_water_byte = *((game_info as *const u8).add(0xD972));

            for bucket_idx in 0..32u32 {
                if (bucket_mask & (1u32 << bucket_idx)) == 0 {
                    continue;
                }

                // Each bucket: +0x0 capacity, +0x4 unused, +0x8 count,
                // +0xC ptr to entity-pointer array.
                let bucket = (gss as *const u8).add(0x28 + bucket_idx as usize * 0x10);
                let count = *(bucket.add(0x8) as *const i32);
                let arr = *(bucket.add(0xC) as *const *const *mut WorldEntity);

                for i in 0..count {
                    let other = *arr.add(i as usize);
                    if other.is_null() || other == this {
                        continue;
                    }
                    let other_b = other as *const u8;

                    // +0x3C "alive/active" flag — polymorphic across
                    // subclasses but uniformly zeroed when the entity
                    // should be skipped by collision.
                    if *(other_b.add(0x3C) as *const u32) == 0 {
                        continue;
                    }
                    // +0xD8: marker set by find_intersections when the
                    // helper says `other` already overlaps with `this`'s
                    // current pose; skip those so we don't get stuck.
                    if *(other_b.add(0xD8)) != 0 {
                        continue;
                    }

                    if my_alliance >= 0 {
                        let other_team = vt_get_team_index(other);
                        if other_team != 0 {
                            let arena: *const TeamArena = &raw const (*world).team_arena;
                            let other_alliance =
                                (*TeamArena::team_header(arena, other_team as usize))
                                    .weapon_alliance;
                            let scheme_byte = if other_alliance == my_alliance {
                                friendly_threshold
                            } else {
                                enemy_threshold
                            };
                            let other_class_is_control =
                                is_control_class((*(other as *const BaseEntity)).class_type);
                            let needed = if my_class_is_control && other_class_is_control {
                                1
                            } else {
                                2
                            };
                            if needed <= scheme_byte {
                                continue;
                            }
                        }
                    }

                    // Sudden-death water-edge gate: when active, worms
                    // moving below the water surface in bucket 1 fail the
                    // move pre-emptively (without ever calling the shape
                    // helper).
                    if sd_water_byte != 0 {
                        let landscape_flag = (*game_info).landscape_scheme_flag != 0;
                        let cavern = (*world).is_cavern != 0;
                        let class_is_worm =
                            (*(this as *const BaseEntity)).class_type == ClassType::Worm;
                        let y_above_threshold = y < Fixed::from_int(17);
                        if (landscape_flag || cavern)
                            && bucket_idx == 1
                            && class_is_worm
                            && y_above_threshold
                        {
                            let level_width = (*world).level_width;
                            let x_in_bounds =
                                (x.to_int() as u32).wrapping_add(4) < level_width.wrapping_add(8);
                            if sd_water_byte > 1 || x_in_bounds {
                                return other;
                            }
                        }
                    }

                    // Helper.vtable[4]: (x, y, other.collision_helper,
                    // Helper.vtable[4]: thiscall — ECX = helper, 5 stack
                    // args, callee cleans up. WA's stock helper here is
                    // `PC_CollisionMask::collision` (0x0057DF70), which
                    // reads `[this+4]` in its prologue, so calling stdcall
                    // (no `this`) crashes with a null deref there.
                    type IntersectFn = unsafe extern "thiscall" fn(
                        this: *mut c_void,
                        self_x: i32,
                        self_y: i32,
                        other_helper: *mut c_void,
                        other_x: i32,
                        other_y: i32,
                    ) -> u32;
                    let helper_vt = *(helper as *const *const usize);
                    let intersects: IntersectFn = core::mem::transmute(*helper_vt.add(4));
                    let other_helper = (*other).collision_helper;
                    let other_x = (*other).pos_x.0;
                    let other_y = (*other).pos_y.0;
                    if intersects(
                        helper,
                        x.to_int(),
                        y.to_int(),
                        other_helper,
                        other_x >> 16,
                        other_y >> 16,
                    ) != 0
                    {
                        return other;
                    }
                }
            }

            core::ptr::null_mut()
        }
    }

    /// Pure Rust port of `WorldEntity__IsMoving` — "is this entity in motion?".
    ///
    /// Returns `true` iff any of `speed_x` (+0x90), `speed_y` (+0x94), or the
    /// three subclass-polymorphic scalars `_field_b0`/`_field_b4`/`_field_b8`
    /// are non-zero. Together with `speed_x`/`speed_y` they form the
    /// canonical "this body is still moving" predicate WA uses across
    /// `WormEntity`, `MineEntity`, `MissileEntity`, `OilDrumEntity`, etc.
    /// (16 callers).
    #[inline]
    pub unsafe fn is_moving_raw(this: *const WorldEntity) -> bool {
        unsafe {
            (*this).speed_x.to_raw() != 0
                || (*this).speed_y.to_raw() != 0
                || (*this)._field_b0 != 0
                || (*this)._field_b4 != 0
                || (*this)._field_b8 != 0
        }
    }
}

/// Sound emitter sub-object embedded in WorldEntity via MSVC multiple inheritance.
///
/// Provides spatial audio support. The `this` pointer for its vtable methods
/// points to the start of this sub-object (WorldEntity+0xE8), not the WorldEntity.
#[repr(C)]
pub struct SoundEmitter {
    /// +0x00: Vtable pointer
    pub vtable: *const SoundEmitterVtable,
    /// +0x04: Unknown field
    pub _unknown_04: u32,
    /// +0x08: Reference count — incremented when an ActiveSoundEntry holds this emitter,
    /// decremented when the entry is released.
    pub local_ref_count: i32,
    /// +0x0C: Number of active local sounds
    pub local_sound_count: i32,
    /// +0x10: Back-pointer to containing WorldEntity
    pub owner: *mut WorldEntity,
}

const _: () = assert!(core::mem::size_of::<SoundEmitter>() == 0x14);

/// Classes 2..=7 (`GameEntity` through `Filter`) are non-physical control
/// containers; the alliance gate uses a more permissive threshold when both
/// sides of a contact are this kind of entity.
#[inline]
fn is_control_class(class: ClassType) -> bool {
    (ClassType::GameEntity..=ClassType::Filter).contains(&class)
}

/// Slot 18 (`GetTeamIndex`) of every WorldEntity vtable — returns the
/// caller's team index (0 = unattributed). The slot offset is `0x48` on
/// every subclass; cast through the base vtable shape to dispatch.
#[inline]
unsafe fn vt_get_team_index(entity: *const WorldEntity) -> u32 {
    type Fn = unsafe extern "thiscall" fn(*const WorldEntity) -> u32;
    unsafe {
        let vtable = *(entity as *const *const usize);
        let f: Fn = core::mem::transmute(*vtable.add(18));
        f(entity)
    }
}

/// Stored target address for [`bridge_update_intersections`]. Set by
/// [`init_addrs`] at hook-install time.
static UPDATE_INTERSECTIONS_ADDR: AtomicU32 = AtomicU32::new(0);

/// Stored target address for [`WorldEntity::construct_raw`]. Set by
/// [`init_addrs`] at hook-install time.
static WORLD_ENTITY_CTOR_ADDR: AtomicU32 = AtomicU32::new(0);

/// Initialise the bridge addresses needed by
/// [`WorldEntity::check_move_collision_raw`] and
/// [`WorldEntity::construct_raw`]. Must be called once at DLL startup
/// before any entity moves or is constructed.
pub unsafe fn init_addrs() {
    UPDATE_INTERSECTIONS_ADDR.store(rb(COLLISION_UPDATE_INTERSECTIONS), Ordering::Relaxed);
    WORLD_ENTITY_CTOR_ADDR.store(rb(CGAMETASK_CONSTRUCTOR), Ordering::Relaxed);
}

/// `CollisionManager::update_intersections` (0x004FBC30) —
/// `__usercall(EDI = gss, ESI = this)`, no stack args, plain RET.
/// ESI/EDI are callee-saved by the platform ABI but we clobber them while
/// loading the call inputs, so push/pop around the call.
#[unsafe(naked)]
unsafe extern "stdcall" fn bridge_update_intersections(_gss: *mut u8, _this: *mut WorldEntity) {
    core::arch::naked_asm!(
        "push edi",
        "push esi",
        "mov edi, dword ptr [esp+12]",  // gss
        "mov esi, dword ptr [esp+16]",  // this
        "mov eax, dword ptr [{addr}]",
        "call eax",
        "pop esi",
        "pop edi",
        "ret 8",
        addr = sym UPDATE_INTERSECTIONS_ADDR,
    );
}

/// Vtable for the SoundEmitter sub-object (0x669CF8, 12 slots).
///
/// Slots [0]-[4] are the sound emitter's own interface.
/// Slots [5]-[11] are inherited BaseEntity base methods.
#[openwa_game::vtable(size = 12, va = 0x00669CF8, class = "SoundEmitter")]
pub struct SoundEmitterVtable {
    /// GetPosition(this, out_x, out_y) — reads pos_x/pos_y via owner
    #[slot(0)]
    pub get_position: fn(this: *const SoundEmitter, out_x: *mut u32, out_y: *mut u32),
    /// GetPosition2 — reads WorldEntity+0x38/0x3C
    #[slot(1)]
    pub get_position2: fn(this: *const SoundEmitter, out_x: *mut u32, out_y: *mut u32),
    /// Destructor
    #[slot(3)]
    pub destructor: fn(this: *mut SoundEmitter, flags: u32) -> *mut SoundEmitter,
    /// HandleMessage — sound queue manager
    #[slot(4)]
    pub handle_message:
        fn(this: *mut SoundEmitter, sender: u32, msg_type: u32, size: u32, data: u32),
}
