[[function]]
va = 0x005714B0
name = "DSSound__LoadEffectWAVs"

[[function]]
va = 0x00571660
name = "DSSound__LoadSpeechBank"
calling_convention = "__stdcall"
custom_storage = true

  [function.signature]
  returns = "void"

  [[function.param]]
  name = "ddgw"
  type = "void *"
  storage = "EAX"

  [[function.param]]
  name = "team_index"
  type = "uint"
  storage = "stack:0x4"

  [[function.param]]
  name = "speech_base_path"
  type = "const char *"
  storage = "stack:0x8"

  [[function.param]]
  name = "speech_dir"
  type = "const char *"
  storage = "stack:0xC"

[[function]]
va = 0x00571A70
name = "DSSound__LoadAllSpeechBanks"
calling_convention = "__stdcall"
custom_storage = true

  [function.signature]
  returns = "void"

  [[function.param]]
  name = "ddgw"
  type = "void *"
  storage = "ESI"

[[function]]
va = 0x00573D50
name = "DSSound__Constructor"

[[function]]
va = 0x00573DB0
name = "DSSound__Destructor"

[[function]]
va = 0x00573DD0
name = "DSSound__Destructor_1"

[[function]]
va = 0x00574310
name = "DSSound__ReleaseChannelBuffers"

[[function]]
va = 0x00574350
name = "DSSound__ReleaseSlotBuffers"

[[function]]
va = 0x00574460
name = "DSSound__SetFrequencyScale"

[[function]]
va = 0x005747F0
name = "DSSound__IsChannelFinished"

[[function]]
va = 0x00574900
name = "DSSound__SetPan"

[[function]]
va = 0x00574980
name = "DSSound__SetChannelVolume"

[[function]]
va = 0x00574A10
name = "DSSound__SetMasterVolume"

[[global]]
va = 0x0066AF20
name = "DSSound__vtable"
