[[function]]
va = 0x0054F4C0
name = "FireEntity__Constructor"

[[function]]
va = 0x0054F680
name = "FireEntity__Free"

[[function]]
va = 0x0054F770
name = "FireEntity__Init"

[[function]]
va = 0x005501A0
name = "FireEntity__HandleMessage"

[[function]]
va = 0x005509E0
name = "FireEntity__ProcessFrame"

[[global]]
va = 0x00669DD8
name = "FireEntity__vtable"
