[[function]]
va = 0x004608E0
name = "GameInfo__InitSession"
calling_convention = "__stdcall"

  [function.signature]
  returns = "void"

  [[function.param]]
  name = "prefix_ptr"
  type = "byte *"

  [[function.param]]
  name = "type_label"
  type = "char *"

[[function]]
va = 0x00460AC0
name = "GameInfo__LoadOptions"

[[function]]
va = 0x00466460
name = "GameInfo__InitTeamsFromLobby"
calling_convention = "__stdcall"

  [function.signature]
  returns = "void"

  [[function.param]]
  name = "prefix_ptr"
  type = "byte *"
