[[function]]
va = 0x0058BC10
name = "Music__Constructor"
calling_convention = "__stdcall"
custom_storage = true

  [function.signature]
  returns = "void"

  [[function.param]]
  name = "this"
  type = "Music *"
  storage = "ESI"

  [[function.param]]
  name = "ids"
  type = "uint"
  storage = "stack:0x4"

  [[function.param]]
  name = "path_ptr"
  type = "const byte *"
  storage = "stack:0x8"

[[function]]
va = 0x0058BC60
name = "Music__ScalarDeletingDtor"

[[function]]
va = 0x0058BC80
name = "Music__Destructor"

[[function]]
va = 0x0058BCE0
name = "Music__StopAndCleanup"

[[function]]
va = 0x0058BD20
name = "Music__PlayTrack"

[[function]]
va = 0x0058BE70
name = "Music__StartMusic"

[[function]]
va = 0x0058BE90
name = "Music__SetPlaylist"

[[function]]
va = 0x0058BEE0
name = "Music__AdvanceTrack"

[[function]]
va = 0x0058BF40
name = "Music__SetVolume"

[[struct]]
name = "Music"
namespace = "/OpenWA"
size = 0x354
rust_path = "openwa_game::audio::music::Music"
