[[function]]
va = 0x00555E20
name = "Task_Team__dtor0_Task_Team"

[[function]]
va = 0x00555F80
name = "Task_Team__save"

[[function]]
va = 0x005560B0
name = "Task_Team__construct_pointers"

[[function]]
va = 0x00556120
name = "Task_Team__select_default_weapon"

[[function]]
va = 0x00556230
name = "Task_Team__find_default_weapon"

[[function]]
va = 0x00556690
name = "Task_Team__advance_worm"

[[function]]
va = 0x00556880
name = "Task_Team__set_worm"

[[function]]
va = 0x00556970
name = "Task_Team__render_panel"

[[function]]
va = 0x00556A40
name = "Task_Team__sub_556A40"

[[function]]
va = 0x00556AD0
name = "Task_Team__render_cursor"

[[function]]
va = 0x00556D00
name = "Task_Team__reset_cursor"

[[function]]
va = 0x00556D30
name = "Task_Team__enable_cursor"

[[function]]
va = 0x00556E90
name = "Task_Team__sub_556E90"

[[function]]
va = 0x00557270
name = "Task_Team__update_reselect"

[[function]]
va = 0x00558BB0
name = "Task_Team__cancel_delay"

[[function]]
va = 0x00558BE0
name = "Task_Team__render_start_delay"

[[function]]
va = 0x00558CF0
name = "Task_Team__play_tick"

[[function]]
va = 0x00558D40
name = "Task_Team__update_start_delay"

[[function]]
va = 0x00558DE0
name = "Task_Team__enquire"

[[function]]
va = 0x00558E30
name = "Task_Team__select_weapon"

[[function]]
va = 0x00558E80
name = "Task_Team__subtract_weapon"

[[function]]
va = 0x00558EE0
name = "Task_Team__reset_select"

[[function]]
va = 0x00558F20
name = "Task_Team__reset_keyboard"

[[function]]
va = 0x00558FD0
name = "Task_Team__process_input"

[[function]]
va = 0x00559080
name = "Task_Team__sub_559080"

[[function]]
va = 0x005592E0
name = "Task_Team__sub_5592E0"

[[function]]
va = 0x00559380
name = "Task_Team__process_panel"

[[function]]
va = 0x005593C0
name = "Task_Team__sub_5593C0"

[[function]]
va = 0x005597A0
name = "Task_Team__process_cursor"

[[function]]
va = 0x0055A0C0
name = "Task_Team__sub_55A0C0"

[[function]]
va = 0x0055A4E0
name = "Task_Team__process_weapon_control"

[[function]]
va = 0x0055A680
name = "Task_Team__process_keyboard"

[[function]]
va = 0x0055A710
name = "Task_Team__process_worm_movement"

[[function]]
va = 0x0055AAC0
name = "Task_Team__find_key_weapons"

[[function]]
va = 0x0055ABC0
name = "Task_Team__process_weapon_select"

[[function]]
va = 0x0055AE50
name = "Task_Team__check_for_replay_request"

[[function]]
va = 0x0055AEB0
name = "Task_Team__check_for_worm_focus"

[[function]]
va = 0x0055B070
name = "Task_Team__sub_55B070"

[[function]]
va = 0x0055B130
name = "Task_Team__sub_55B130"

[[function]]
va = 0x0055B190
name = "Task_Team__sub_55B190"

[[function]]
va = 0x0055B220
name = "Task_Team__sub_55B220"
