[[function]]
va = 0x0050CED0
name = "Task_Worm__qsort_cmp"

[[function]]
va = 0x0050CF10
name = "Task_Worm__construct_pointers"

[[function]]
va = 0x0050D370
name = "Task_Worm__calc_highest_fall"

[[function]]
va = 0x0050D830
name = "Task_Worm__sub_50D830"

[[function]]
va = 0x0050D910
name = "Task_Worm__sub_50D910"

[[function]]
va = 0x0050DC00
name = "Task_Worm__sub_50DC00"

[[function]]
va = 0x0050F6B0
name = "Task_Worm__create_cross"

[[function]]
va = 0x00512E80
name = "Task_Worm__calc_sprite"

[[function]]
va = 0x00513530
name = "Task_Worm__last_worm_of_ally"

[[function]]
va = 0x005135C0
name = "Task_Worm__create_donor_card"

[[function]]
va = 0x00513810
name = "Task_Worm__detonate"

[[function]]
va = 0x00513980
name = "Task_Worm__setup_JetPacking"

[[function]]
va = 0x005139E0
name = "Task_Worm__calc_jetpack"

[[function]]
va = 0x00513B40
name = "Task_Worm__update_jetpack"

[[function]]
va = 0x00513C50
name = "Task_Worm__handle_JetPacking"

[[function]]
va = 0x00513D90
name = "Task_Worm__control_jetpack"

[[function]]
va = 0x00513EB0
name = "Task_Worm__control_parachute"

[[function]]
va = 0x00513F00
name = "Task_Worm__control_rope_0"

[[function]]
va = 0x00513FF0
name = "Task_Worm__sub_513FF0"

[[function]]
va = 0x005140E0
name = "Task_Worm__control_walk"

[[function]]
va = 0x005144B0
name = "Task_Worm__update_smoke"

[[function]]
va = 0x005145B0
name = "Task_Worm__update_skid"

[[function]]
va = 0x005146D0
name = "Task_Worm__update_bubbles"

[[function]]
va = 0x005147C0
name = "Task_Worm__update_damage_display"

[[function]]
va = 0x00514AC0
name = "Task_Worm__update_movement"

[[function]]
va = 0x00514E00
name = "Task_Worm__flush_sounds"

[[function]]
va = 0x00514EA0
name = "Task_Worm__update_sounds"

[[function]]
va = 0x00514F80
name = "Task_Worm__Baseball_Jingle"

[[function]]
va = 0x005150D0
name = "Task_Worm__fire_sound"

[[function]]
va = 0x00515130
name = "Task_Worm__stop_worm_sound"

[[function]]
va = 0x00515180
name = "Task_Worm__stop_fire_sound"

[[function]]
va = 0x005151D0
name = "Task_Worm__try_to_aim"

[[function]]
va = 0x00515240
name = "Task_Worm__update_idle_anims"

[[function]]
va = 0x00515530
name = "Task_Worm__sub_515530"

[[function]]
va = 0x005155A0
name = "Task_Worm__update_jingle"

[[function]]
va = 0x00516950
name = "Task_Worm__sub_516950"

[[function]]
va = 0x00516A90
name = "Task_Worm__sub_516A90"

[[function]]
va = 0x00516B10
name = "Task_Worm__sub_516B10"

[[function]]
va = 0x00516B40
name = "Task_Worm__sub_516B40"

[[function]]
va = 0x00516B90
name = "Task_Worm__sub_516B90"

[[function]]
va = 0x00516CA0
name = "Task_Worm__setup_Standing"

[[function]]
va = 0x00516DA0
name = "Task_Worm__calc_breath"

[[function]]
va = 0x00516E90
name = "Task_Worm__handle_Standing"

[[function]]
va = 0x00517100
name = "Task_Worm__setup_Aiming"

[[function]]
va = 0x00517790
name = "Task_Worm__handle_Powerup"

[[function]]
va = 0x00517850
name = "Task_Worm__setup_PreFiring"

[[function]]
va = 0x00517BE0
name = "Task_Worm__handle_PreFiring"

[[function]]
va = 0x00517F00
name = "Task_Worm__setup_PostFiring"

[[function]]
va = 0x005180E0
name = "Task_Worm__handle_PostFiring"

[[function]]
va = 0x005181D0
name = "Task_Worm__setup_RepeatFiring"

[[function]]
va = 0x00518280
name = "Task_Worm__handle_RepeatFiring"

[[function]]
va = 0x00518340
name = "Task_Worm__setup_Punching"

[[function]]
va = 0x005183C0
name = "Task_Worm__handle_Punching"

[[function]]
va = 0x005186A0
name = "Task_Worm__setup_Drilling"

[[function]]
va = 0x00518770
name = "Task_Worm__handle_Drilling"

[[function]]
va = 0x00518A50
name = "Task_Worm__setup_Kamikaze"

[[function]]
va = 0x00518C10
name = "Task_Worm__handle_Kamikaze"

[[function]]
va = 0x00519140
name = "Task_Worm__handle_Suicide"

[[function]]
va = 0x005196D0
name = "Task_Worm__setup_Teleporting"

[[function]]
va = 0x00519740
name = "Task_Worm__handle_Teleporting"

[[function]]
va = 0x005199B0
name = "Task_Worm__sub_5199B0"

[[function]]
va = 0x00519A60
name = "Task_Worm__update_batrope"

[[function]]
va = 0x00519D80
name = "Task_Worm__setup_FiringBatrope"

[[function]]
va = 0x00519E50
name = "Task_Worm__setup_Batroping"

[[function]]
va = 0x00519F00
name = "Task_Worm__handle_Batroping"

[[function]]
va = 0x0051A3B0
name = "Task_Worm__setup_Bungeing"

[[function]]
va = 0x0051A400
name = "Task_Worm__handle_Bungeing"

[[function]]
va = 0x0051A540
name = "Task_Worm__sub_51A540"

[[function]]
va = 0x0051A680
name = "Task_Worm__fire_parachute"

[[function]]
va = 0x0051A710
name = "Task_Worm__setup_Parachuting"

[[function]]
va = 0x0051A750
name = "Task_Worm__setup_FiringNuke"

[[function]]
va = 0x0051A7B0
name = "Task_Worm__setup_Axeing"

[[function]]
va = 0x0051A8F0
name = "Task_Worm__handle_BlowTorching"

[[function]]
va = 0x0051AC50
name = "Task_Worm__sub_51AC50"

[[function]]
va = 0x0051AD10
name = "Task_Worm__handle_Axeing"

[[function]]
va = 0x0051B390
name = "Task_Worm__perform_air_missile"

[[function]]
va = 0x0051B4C0
name = "Task_Worm__perform_air_strike"

[[function]]
va = 0x0051B520
name = "Task_Worm__perform_air_drop"

[[function]]
va = 0x0051B640
name = "Task_Worm__perform_air_special"

[[function]]
va = 0x0051C060
name = "Task_Worm__calc_aiming"

[[function]]
va = 0x0051C390
name = "Task_Worm__release_weapon_0"

[[function]]
va = 0x0051CA90
name = "Task_Worm__aim_focus"

[[function]]
va = 0x0051CB60
name = "Task_Worm__release_focus"

[[function]]
va = 0x0051CEF0
name = "Task_Worm__render_power"

[[function]]
va = 0x0051CFC0
name = "Task_Worm__update_crosshair"

[[function]]
va = 0x0051D100
name = "Task_Worm__control_aim"

[[function]]
va = 0x0051D9F0
name = "Task_Worm__render_sight"

[[function]]
va = 0x0051DB20
name = "Task_Worm__bullet2object"

[[function]]
va = 0x0051E8C0
name = "Task_Worm__fire_utility"

[[function]]
va = 0x0051EBE0
name = "Task_Worm__fire_quake"

[[function]]
va = 0x0051F1C0
name = "Task_Worm__initialise_herd"

[[function]]
va = 0x0051F240
name = "Task_Worm__update_herd"

[[function]]
va = 0x0051FD90
name = "Task_Worm__analyse_sight"
