[[function]]
va = 0x00504CC0
name = "Task_OilDrum__ctor1_Task_OilDrum"

[[function]]
va = 0x00504D90
name = "Task_OilDrum__collide"

[[function]]
va = 0x00504DF0
name = "Task_OilDrum__detonate"

[[function]]
va = 0x00505000
name = "Task_OilDrum__render"

[[function]]
va = 0x00505420
name = "Task_OilDrum__sub_505420"
