[[function]]
va = 0x00501C70
name = "Task_Canister__dtor0_Task_Canister"

[[function]]
va = 0x00501CB0
name = "Task_Canister__ctor1_Task_Canister"

[[function]]
va = 0x00501D80
name = "Task_Canister__save"

[[function]]
va = 0x00501E30
name = "Task_Canister__collide"

[[function]]
va = 0x00501E80
name = "Task_Canister__calc_sprite"

[[function]]
va = 0x00501EE0
name = "Task_Canister__render"

[[function]]
va = 0x00501F60
name = "Task_Canister__emit_gass"

[[function]]
va = 0x00502030
name = "Task_Canister__detonate"

[[function]]
va = 0x00502090
name = "Task_Canister__message"

[[function]]
va = 0x00502400
name = "Task_Canister__sub_502400"
